### ISSUE TITLE
Copy strings to clipboard without quotes

### ISSUE THREAD

**Issue by NicoWeio** [vuejs/devtools#1002]
### What problem does this feature solve?
I find it really annoying how copied strings from the data inspector always include double-quotes. Should that really be the default behaviour?

### What does the proposed API look like?
At the moment, the clipboard value comes from here:
https://github.com/vuejs/vue-devtools/blob/21552134f022be2b8976d205a5c6a23f5ef77fc7/src/devtools/components/DataField.vue#L474
https://github.com/vuejs/vue-devtools/blob/591c1c235f43ab201d4ca5c1e2ab00be4ca3b46f/src/util.js#L616
https://github.com/vuejs/vue-devtools/blob/591c1c235f43ab201d4ca5c1e2ab00be4ca3b46f/src/util.js#L115

There would be many ways to change that behaviour, but first I would like to know if you agree.

**Comment by Akryum** [comment]
We actually copy the JSON representation of the value.

**Comment by NicoWeio** [comment]
I see. Copying all values in their plain form instead of their JSON representation might be a useful setting, though.

**Comment by g-plane** [comment]
Can I submit a PR for adding a setting for this option?

**Comment by Kapcash** [comment]
Still waiting for this feature! 
I do expect the copy to actually copy the plain value if it's a primitive (string, number, boolean...) and a JSON representation for any other type.

This would do a nice "Good first issue" PR I think :)
