### ISSUE TITLE
Electron Unexpected token ... at createScript

### ISSUE THREAD

**Issue by dillingham** [vuejs/devtools#1071]
### Version
5.1.1

### Browser and OS info
Mac

### Steps to reproduce
> sudo npm install -g @vue/devtools

> vue-devtools

### What is expected?
it to load the electron app

### What is actually happening?
electron app starts up
its alerts a js exception

---
```
Uncaught Exception:
/usr/local/lib/node_modules/@vue/devtools/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/devtools/node_modules/ws/index.js:3:19)
```

**Comment by foxted** [comment]
Experiencing the same issue here.

**Comment by jarrodwhitley** [comment]
Experiencing same error as well.

**Comment by dillingham** [comment]
Thought maybe it was an old version of node

But running >9.0 and spread operators were introduced in 8.3 it seams.

**Comment by fwx426328** [comment]
the same issue

**Comment by edsharp** [comment]
Same issue. FWIW switching the electron dependency back to `"electron": "1.7.11"` (from the current `1.7.16`) and the issue goes away

**Comment by barrymortenson** [comment]
@dillingham were you able to get any resolution on this issue? I have tried multiple versions of vue-devtools and electron but have been unable to get it to work.

**Comment by dillingham** [comment]
@barrymortenson no luck yet. I tried changing the electron version as @edsharp suggested manually in `node_modules/@vue/devtools/package.json` and  `npm install` and got the same error when  I `node_modules/.bin/vue-devtools`.. @edsharp how did you get it working? :)

**Comment by edsharp** [comment]
@dillingham 

```diff
diff --git a/shells/electron/package.json b/shells/electron/package.json
index a2daa4a..e5dac30 100644
--- a/shells/electron/package.json
+++ b/shells/electron/package.json
@@ -20,7 +20,7 @@
   "license": "MIT",
   "dependencies": {
     "cross-spawn": "^5.1.0",
-    "electron": "1.7.16",
+    "electron": "1.7.11",
     "express": "^4.16.2",
     "ip": "^1.1.5",
     "socket.io": "^2.0.4"
diff --git a/shells/electron/yarn.lock b/shells/electron/yarn.lock
index f7482b2..9c9e99d 100644
--- a/shells/electron/yarn.lock
+++ b/shells/electron/yarn.lock
@@ -967,10 +967,10 @@ electron-download@^3.0.1:
     semver "^5.3.0"
     sumchecker "^1.2.0"

-electron@1.7.16:
-  version "1.7.16"
-  resolved "https://registry.yarnpkg.com/electron/-/electron-1.7.16.tgz#40e6b5553e3a87ce7ea52eb05f7926bc40cab11c"
-  integrity sha512-k17+2K3hny6g1etWMkWvzEL06yapZGpqG66O3e5vxfzeHT3FgqrNa3xRF7znjaqvWQmmEdGFdSktQADjUZ0gog==
+electron@1.7.11:
+  version "1.7.11"
+  resolved "https://registry.yarnpkg.com/electron/-/electron-1.7.11.tgz#993b6aa79e0e79a7cfcc369f4c813fbd9a0b08d9"
+  integrity sha1-mTtqp54OeafPzDafTIE/vZoLCNk=
   dependencies:
     "@types/node" "^7.0.18"
     electron-download "^3.0.1"
```

I just made that change to package.json, ran `yarn` then `npm start`.

It worked with both node `10.16.2` and `12.10.0`.

**Comment by Noctsyndrome** [comment]
same issue here

**Comment by Noctsyndrome** [comment]
a temporary solution，
1. go to the devtool path ( ~node_modules\@vue\devtools ), and run `node server.js`;
2. go ~node_modules\@vue\devtools\node_modules\electron\dist, open electron app;
3. drag app.html from ~node_modules\@vue\devtools into the electron app;

now it should work.

**Comment by barrymortenson** [comment]
@Noctsyndrome, thank you that helped a ton. I ended up creating a couple aliases based on your solution to make it faster to startup.

Assuming @vue/devtools is installed globally `npm i -g @vue/devtools`, here are the commands to run the server and the electron app from the terminal (run each in their own tab/window):

```
node ./node_modules/@vue/devtools/server.js
```
```
/usr/local/lib/node_modules/@vue/devtools/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron ./node_modules/@vue/devtools/app.html
```

**Comment by andresilva-cc** [comment]
> @Noctsyndrome, thank you that helped a ton. I ended up creating a couple aliases based on your solution to make it faster to startup.
> 
> Assuming @vue/devtools is installed globally `npm i -g @vue/devtools`, here are the commands to run the server and the electron app from the terminal (run each in their own tab/window):
> 
> ```
> node ./node_modules/@vue/devtools/server.js
> ```
> 
> ```
> /usr/local/lib/node_modules/@vue/devtools/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron ./node_modules/@vue/devtools/app.html
> ```

I'm using `nativescript-vue` and I'm trying the following:

I did not install `@vue/devtools` globally.
`node [...]/server.js` worked perfectly, but there's no electron folder inside `@vue/devtools/node_modules`.

I see that `electron` was installed in my project `node_modules` folder, so I tried the following:
`./node_modules/electron/dist/electron ./node_modules/@vue/devtools/app.html`
It returns:

```[30665:0414/163804.498813:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that [hidden]/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
[1]    30665 trace trap  ./node_modules/electron/dist/electron ./node_modules/@vue/devtools/app.html```

I tried running `server.js` with sudo, but that doesn't work either.
