### ISSUE TITLE
Vuex store not getting updated with Nuxt

### ISSUE THREAD

**Issue by nurdism** [vuejs/devtools#1113]
### Version
5.3.2

### Browser and OS info
Chrome 78.0.3904.97 (Official Build) (64-bit) / Windows 10

### Steps to reproduce
This issue was closed (#935), but is still an issue with nuxt.

When using `nuxtServerInit`, to mutate the sate, the devtools will not sync the state once page is loaded.

### What is expected?
state to be synced

### What is actually happening?
state is not synced

**Comment by Valentin-Seehausen** [comment]
+1

**Comment by Valentin-Seehausen** [comment]
Erm... ok that sounds very silly:

It works now. I had to turn on recording. The small red button on top of the commit list of devtools.

Don't know why and when I turned it off. Sorry. :-D

**Comment by rayoplateado** [comment]
> Erm... ok that sounds very silly:
> 
> It works now. I had to turn on recording. The small red button on top of the commit list of devtools.
> 
> Don't know why and when I turned it off. Sorry. :-D

Silly? but not alone! I've waste some time for the same reason. It was paused.

**Comment by jpedro73** [comment]
SAME ISSUE 

### Browser and OS info
Chrome Version 98.0.4758.82 / windows11 v10.0.22000 / Nuxt @2.15.8





### Steps to reproduce
Use Nuxt,  open the devtools, update the status of the vuex in your app and you will see that vuex state is not updated

### What is expected?
The vuex tab update the state.

### What is actually happening?
Vuex don't update the state
