### ISSUE TITLE
Warn if older version of Vue is used

### ISSUE THREAD

**Issue by ghost** [vuejs/devtools#1181]
### What problem does this feature solve?
This helps us find if a website uses older version of Vue and helps us inform them, or if that's ours, upgrade update Vue version
Just show the  Vue-Devtools logo and a small warning logo in bottom-right position.

This is been inspired by react devtools

### What does the proposed API look like?
See the implementation of react devtools

**Comment by konpeki622** [comment]
Looks like it has been enhanced on v6.
