### ISSUE TITLE
Store as a global variable

### ISSUE THREAD

**Issue by Renato66** [vuejs/devtools#1200]
### What problem does this feature solve?
Sometimes i need to extract some data from arrays/objects, so I copy value and paste on console to work with;
![Captura de Tela 2020-05-13 às 12 40 07](https://user-images.githubusercontent.com/9284273/81834119-ef9bb680-9516-11ea-8600-aee9853815a5.png)
A new option on dots: a copy to variable, it could be stored same as chrome `store as global variable`
![Captura de Tela 2020-05-13 às 12 41 30](https://user-images.githubusercontent.com/9284273/81834273-1ce86480-9517-11ea-9917-b07c65264f4f.png)

### What does the proposed API look like?
```
function storeAsGlobal (value) {
  let exit = false
  let cont = 0
  do {
    if (window[`temp${count}`] === undefined){
      window[`temp${count}`] = value
      exit = true
      console.log(`Stored as temp${count}`, window.[`temp${count}`])
    }
    cont++
  } while(exit)
}
```

**Comment by Benez11** [comment]
Check out this thread: [https://github.com/vuejs/vue-devtools/issues/613](url)

**Comment by Benez11** [comment]
Check out this thread: https://github.com/vuejs/vue-devtools/issues/613

**Comment by Renato66** [comment]
@Benez11 cool, i think this will help me alot 👍
