### ISSUE TITLE
Persist state inspector section expanded state

### ISSUE THREAD

**Issue by peter31990** [vuejs/devtools#1391]
### What problem does this feature solve?
Why data in component inspector are always automatically expanded? It is very annoying when everything is expanded and it is difficult to find the necessary properties.

### What does the proposed API look like?
All properties should be collapsed.

**Comment by piotrmachacki** [comment]
I agree. It would be nice if data, computed etc. would be automatically collapsed and you wouldn't have to waste time collapsing it to make the view clearer.
