### ISSUE TITLE
mac m1 electron issue

### ISSUE THREAD

**Issue by anothergituser** [vuejs/devtools#1394]
### Version
6.0.0-beta.7

### Browser and OS info
macos m1

### Steps to reproduce
npm install @vue/devtools

### What is expected?
install vue/devtools

### What is actually happening?
Install will fail because https://github.com/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip does not exist.

There is a beta although, https://github.com/electron/electron/releases/download/v13.0.0-beta.9/electron-v13.0.0-beta.9-darwin-arm64.zip but i don't know how to make it use that version and if it will work. Thanks

**Comment by YosefOberlander** [comment]
same issue here.

**Comment by jixb** [comment]
me too

**Comment by Akryum** [comment]
Vue devtools 6 beta already [uses Electron 12](https://github.com/vuejs/vue-devtools/blob/ee6005c0043ca91949c06c30b323754844da1358/packages/shell-electron/package.json#L28). M1 support was added in Electron 11, so it should work. Otherwise, I don't have a M1 so I can't test it anyway...

**Comment by Akryum** [comment]
> ### Version
> 
> 6.0.0-beta.7

Are you sure that your `@vue/devtools` version is 6.0.0-beta.7 in your project ?

**Comment by jonathanjanssens** [comment]
I can confirm that `npm i -g @vue/devtools@6.0.0-beta.12` does install and seems to be working fine on M1

**Comment by YosefOberlander** [comment]
I can confirm that yarn global add @vue/devtools@6.0.0-beta.12 installs and works perfectly
