### ISSUE TITLE
Can't edit data of component with no setup function

### ISSUE THREAD

**Issue by syberon** [vuejs/devtools#1427]
### Version
6.0.0-beta.8

### Browser and OS info
Vivaldi 3.7.2218.58 / Windows 10

### Steps to reproduce
1. Open inspector on page with Vue 3 script
2. Go to Vue tab
3. Select any variable in 'data' and try to change its value

### What is expected?
Variable value changed to new

### What is actually happening?
Variable value is not changing and there are errors in Console:

```
backend.js:388 An error occured in hook editComponentState
    callHandlers @ backend.js:388
    callHook @ backend.js:27
    editComponentState @ backend.js:132
    editComponentState @ backend.js:803
    (anonymous) @ backend.js:1061
    emit @ backend.js:5799
    _emit @ backend.js:4141
    (anonymous) @ backend.js:4073
    (anonymous) @ backend.js:4073
    listener @ backend.js:6796
    postMessage (async)
    n @ proxy.js:1

backend.js:389 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.editState (backend.js:3376)
    at backend.js:3928
    at DevtoolsHookable.callHandlers (backend.js:385)
    at DevtoolsApi.callHook (backend.js:27)
    at DevtoolsApi.editComponentState (backend.js:132)
    at Object.editComponentState (backend.js:803)
    at Bridge.<anonymous> (backend.js:1061)
    at Bridge.emit (backend.js:5799)
    at Bridge._emit (backend.js:4141)
```

**Comment by Akryum** [comment]
Please provide a runnable minimal reproduction.

**Comment by syberon** [comment]
I created a minimal application to reproduce this issue.
[http://sybernas.myqnapcloud.com:8080/share.cgi?ssid=0rbwla0](url)

I found that this issue is only affects the applications that uses Options API - application that uses Composition API doesn't have this problem.

**Comment by enzolaurent** [comment]
I have the same issue with Vue 3.0.6, I didn't find why.

Version : 6.0.0 beta 8
OS : Windows 10
Chrome 90.0.4430.93

**Comment by EbashuOnHolidays** [comment]
I have the same issue with Vue 3.0.6. This happens when I change `data` values.

![Screenshot from 2021-04-30 23-03-36](https://user-images.githubusercontent.com/20097205/116748797-a040e580-aa08-11eb-830b-e5635c04df76.png)

Version : 6.0.0 beta 8
OS : Mint 20.1
Chrome 90.0.4430.93

**Comment by EbashuOnHolidays** [comment]
The error disappeared after installing version 6.0.0 beta 7

**Comment by doingandlearning** [comment]
I'm still seeing this error on 6.0.0 beta 8.

**Comment by daveberning** [comment]
This is still an issue as of `v6.0.0 beta 18`...

**Comment by daveberning** [comment]
@Akryum here is a reproduction repo: https://github.com/daveberning/do-airports-example

There are airport objects in the `data` directory. When trying to modify that data in the `App.vue` in the DevTools, I get the error specified above.

Vue DevTools: `v6.0.0 beta 18`
Vue: `3.2.12`
OS: `11.4`
Browser: Edge: `93.0.961.52`
