### ISSUE TITLE
Plugins not detected if createApp is delayed by async code

### ISSUE THREAD

**Issue by glen-84** [vuejs/devtools#1475]
### Version
6.0.0-beta.13

### Browser and OS info
Chrome 91 / Windows 10

### Steps to reproduce
```ts
setTimeout(() => {
    const app = createApp(App)
        .use(store, storeInjectionKey)
        .use(router);

    app.mount("#app");
}, 1000); // You may need to increase this.
```

### What is expected?
Dev tools plug-ins should load.

### What is actually happening?
Dev tools plug-ins don't load (unless you close and reopen browser dev tools).

---
I have async code running to load external data that is used to configure some of the Vue.js plugins. It seems that any such delay is preventing the dev tools from detecting the plugins (router, vuex).

You can reproduce using `setTimeout` as shown above, but I'm actually using async/await.

I'm not yet sure how vue-devtools performs the detection, but is it possible to delay that until the app is created/mounted?

If not, is there a global function that I can call after creating/mounting the application, to tell the vue-devtools that the plugins are available?

**Comment by Akryum** [comment]
Please provide a runnable reproduction. I don't reproduce on my side.

**Comment by Akryum** [comment]
https://github.com/vuejs/vue-devtools/commit/5639e700511e45d076ec95b3957494896c8a2357#diff-f5c62042284ec5abc161888191e660a206149b4f19f0a4721f85a9370fb19714R52

**Comment by glen-84** [comment]
@Akryum,

Thanks for looking into this. I will work on a full reproduction repo later today or tomorrow.

**Comment by glen-84** [comment]
You can reproduce with this simple Vue CLI app: https://github.com/glen-84/vue-devtools-issue.

Important notes:

1. Vue itself is detected, just not the plugins (router, vuex).
2. The initial load will be fine (if dev-tools was not open).
3. While the dev-tools are open, refresh the page, and the plugins will disappear.
4. Close and reopen the dev-tools, and the plugins will again appear.

![vue-devtools-issue](https://user-images.githubusercontent.com/261509/121356642-53b6c700-c931-11eb-8dae-92a3438b7762.gif)

**Comment by Akryum** [comment]
The plugins are active otherwise you won't get the tags on the components. Is it just custom inspectors no showing up?

**Comment by Akryum** [comment]
Also you can go to the 'Devtools Plugins...' menu to check if they are there

**Comment by glen-84** [comment]
You're right! I didn't realise that. It looks like both the custom inspectors, as well as the timeline stuff is missing.

**Comment by Akryum** [comment]
@posva isn't this caused by the installed check you added in the router plugin?

**Comment by posva** [comment]
Do you mean this: https://github.com/vuejs/vue-router-next/blob/master/src/devtools.ts#L57-L58 ?
In my experience it works when reloading

**Comment by glen-84** [comment]
@Akryum Were you able to reproduce the issue? I would really love to be able to use these dev-tool plugins. 🙂

**Comment by glen-84** [comment]
This appears to be fixed! 🎉

Note: If the page takes a while to load, messages like `Inspector X not found` will be displayed until the page has loaded.

**Comment by andreasvirkus** [comment]
Hot relaod still breaks devtools, a workaround currently is to

1. close the browser's devtools panel
2. reload the page
3. open up the devtools

If you don't reload the page _or_ if you don't close the devtools when reloading, then Vue devtools errors out with this:

```
TypeError: instance.$on is not a function
    at mark (backend.js:4422:14)
    at captureId (backend.js:4156:5)
    at getComponentParents (backend.js:4160:3)
    at backend.js:4602:64
    at DevtoolsHookable.callHandlers (backend.js:708:17)
    at DevtoolsApi.callHook (backend.js:200:29)
    at DevtoolsApi.walkComponentParents (backend.js:278:32)
    at sendSelectedComponentData (backend.js:1437:57)
    at Bridge.<anonymous> (backend.js:2083:47)
    at Bridge.emit (backend.js:8443:5)
callHandlers @ backend.js:711
callHook @ backend.js:200
walkComponentParents @ backend.js:278
sendSelectedComponentData @ backend.js:1437
(anonymous) @ backend.js:2083
emit @ backend.js:8443
_emit @ backend.js:6446
(anonymous) @ backend.js:6372
(anonymous) @ backend.js:6372
listener @ backend.js:11997
postMessage (async)
n @ proxy.js:1

backend.js:2791 Error: Timed out getting app record for app
    at backend.js:1111:14
```

![Screenshot 2022-08-09 at 17 22 39](https://user-images.githubusercontent.com/9140811/183673952-ffe9b6b4-3b9d-4a80-a65c-e514de9b2695.png)
