### ISSUE TITLE
Wrong timeline screenshot size

### ISSUE THREAD

**Issue by jerometremblay** [vuejs/devtools#1487]
### Version
6.0.0-beta.14

### Browser and OS info
OSX Big Sur

### Steps to reproduce
Change some states, then hover over the timeline.

### What is expected?
The application should retain the original zoom level

### What is actually happening?
The original app is zoomed

---
I recorded the behavior on this video https://youtu.be/QlSS5RruSn0

**Comment by Akryum** [comment]
I guess it's the screenshots having an incorrect size. Maybe an HiDPI issue? Do you have the issue if the viewport is in landscape?

**Comment by jerometremblay** [comment]
How would you change that?

I tried fixing the body with a px width, no changes.

I'm on a macbook, so the HiDPI is a possibility.

**Comment by jerometremblay** [comment]
The behavior changes when I undock the developer pane.
There is no zoom effect, but the screenshot is not updated either. It's not showing in the video somehow, but when I hover the mouse over the timeline I have the "no image" icon flashing in the chrome window.

https://youtu.be/UkVArOoh7yU

**Comment by Akryum** [comment]
For the undocked devtools issue, afaik it's a Chrome bug.

**Comment by Akryum** [comment]
For the original issue, did you change the windows size **after** using the Vue application (and thus making screenshots on the timeline)?

**Comment by jerometremblay** [comment]
No, the browser window is never resized.

While testing this just now, i noticed something else, the zoom sometime is increasing even more while i scroll through the timeline.

**Comment by symmetriq** [comment]
Same issue here.
macOS 11.6.2 + Chrome 96

Screenshots are really zoomed in, look bad, and are just distracting without providing any value. Would appreciate an option to just disable screenshots altogether.

**Comment by Akryum** [comment]
> Would appreciate an option to just disable screenshots altogether

It already exists

**Comment by symmetriq** [comment]
> > Would appreciate an option to just disable screenshots altogether
> 
> It already exists

Thanks…found it. Didn't realize there were more settings in "..." menu that are only visible when the timeline is selected.
