### ISSUE TITLE
Unable to add or edit values in vuex root pane

### ISSUE THREAD

**Issue by 185driver** [vuejs/devtools#1488]
### Version
6.0.0-beta.14

### Browser and OS info
Chrome 92.0.4515.59 beta / Windows 10

### Steps to reproduce
1. Open vue dev tools and navigate to Vuex section.
2. Attempt to add or edit a state value in the Root window pane (checkbox, text, etc)

### What is expected?
Adding or editing state using the controls provided should be permitted.

### What is actually happening?
If a checkbox, the checkbox value does not change. If a text value, the string can be edited, but won't save. If a   or - key, no increment or decrement occurs.

**Comment by 185driver** [comment]
I'm familiar with creating a repro of a JS issue using something like CodePen, but how does one go about creating a repro of an issue like this one?

**Comment by Akryum** [comment]
You can create a repository of a vue app with vuex on which I can reproduce the issue.
