### ISSUE TITLE
Vue 3 extension

### ISSUE THREAD

**Issue by AdrigomRoc** [vuejs/devtools#1498]
### Version
6.0.0-beta.15

### Browser and OS info
Chrome / Windows 10

### Steps to reproduce
All the projects that I have created of VUE 3 the plugin does not detect me that it is VUE

### What is expected?
Be able to use the Vue plugin in chrome

### What is actually happening?
It always stays in gray and puts vue.js not detected

**Comment by Akryum** [comment]
Did you follow the troubleshooting steps? https://devtools.vuejs.org/guide/faq.html#the-vue-devtools-don-t-show-up
