### ISSUE TITLE
Root component not updating in the inspector when it's not the first app on the page

### ISSUE THREAD

**Issue by LogicAndTrick** [vuejs/devtools#1500]
### Version
6.0.0-beta.15

### Browser and OS info
Chrome 91 / Firefox 89 / Windows 10

### Steps to reproduce
1. Save the HTML below and open in a browser
2. Open the dev tools and select "second-app" from the app list
3. Select the root component and note that the value in the component is 1
4. Click the button in the second app to increase the value

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Test</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/3.1.3/vue.global.min.js"></script>
    </head>
    <body>
        <div id="app1">First app <div>{{value}}</div><button type="button" v-on:click="value++">Click me</button></div>
        <div id="app2">Second app <div>{{value}}</div><button type="button" v-on:click="value++">Click me</button></div>
        <script>
            const app = {
                data() { return {value: 1}; }
            };
            Vue.createApp({ name: 'first-app', ...app }).mount("#app1");
            Vue.createApp({ name: 'second-app', ...app }).mount("#app2");
        </script>
    </body>
</html>
```

### What is expected?
The value in the devtools inspector updates after clicking the button.

### What is actually happening?
The value does not update in the devtools inspector until the force refresh button is clicked.

---
![repro animation](https://user-images.githubusercontent.com/3071180/124233871-a9f4df80-db56-11eb-9551-bc3873d70f84.gif)

**Comment by konpeki622** [comment]
When only one instance was mounted, the root id was defined as `0:root` and the id of child components was `0: a positive number`. If the other instance was mounted, like 'second-app', the root id was defiend as `1:1`, which expected to be `1:root`. To fix it, I think the logic of component id generation should be optimized.
