### ISSUE TITLE
Component list order keeps jumping around

### ISSUE THREAD

**Issue by bobvandevijver** [vuejs/devtools#1503]
### Version
6.0.0-beta.15

### Browser and OS info
Edge 91 / Windows 10

### Steps to reproduce
I'm seeing this quite often, with multiple projects, but I do not have an exact reproducer at this time. However, it seems to be happening mostly with animated components, with both Vue 2 as Vue 3.

### What is expected?
It should be kept in a constant order.

### What is actually happening?
The components keep jumping around.

![jump-recording](https://user-images.githubusercontent.com/1835343/124429166-d171c500-dd6d-11eb-839d-2d6848cde16b.gif)

**Comment by yzqdev** [comment]
I have the same issue, too. At first I thought it was the ui lib or my other chrome extensions that caused this problem. Now I guess it's a bug.
