### ISSUE TITLE
Need ability to distinguish multiple standalone devtool instances 

### ISSUE THREAD

**Issue by jaredmcateer** [vuejs/devtools#1505]
### What problem does this feature solve?
We have an application that swaps iframes, so we need to run  multiple versions of the standalone devtools listening on different ports and it's difficult quickly determine which devtools instance matches the currently active iframe. 

### What does the proposed API look like?
The most simple solution I can think of is simply appending  "`- <host>:<port>`" to the title bar of the electron shell.

**Comment by Akryum** [comment]
Fixed in 72d00f11de5bb7e57b960377ee41fc8197c2bb16 (display page title)
