### ISSUE TITLE
Cannot find Vue tab in Brave's Dev tools

### ISSUE THREAD

**Issue by cooldevcodes** [vuejs/devtools#1506]
### Version
6.0.0-beta.15

### Browser and OS info
Brave Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64) and macOS

### Steps to reproduce
Open a Vue page which runs on Vite 2.4.1. The dev tool can detect the page as a Vue page but Vue tab in Brave's dev tools does not show.

### What is expected?
Vue tab in Brave's dev tools shows and works properly

### What is actually happening?
The dev tool can detect the page as a Vue page but Vue tab in Brave's dev tools does not show.

**Comment by MarcoNaik** [comment]
Im having the same problem on firefox

Running last version on arch linux.

**Comment by officiallymarky** [comment]
Same issue, works in Chrome

**Comment by cooldevcodes** [comment]
I created a project using Vue CLI and Vue tab in Brave's dev tools can be shown. Maybe it is an incompatible issue of Vue Dev Tools with Vite.

**Comment by vkbishu** [comment]
I am using Chrome for development and I am also facing the same issue. I am using "Vue.js devtools 6.0.0 beta 15". 
I have tried disabling the stable version and reopen the page. But the issue remains the same.

**Comment by cooldevcodes** [comment]
Not sure why. But now Vue DevTools works with Brave version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64) and vite 2.5.1
