### ISSUE TITLE
Vue3.0 cannot be used in Firefox. Vue2.0 can

### ISSUE THREAD

**Issue by qq757622960** [vuejs/devtools#1522]

**Comment by RomainLanz** [comment]
Hey! 👋 

I second this.

Latest release of the Vue DevTools does not work with Vue 3.

I am getting the following error in the console:

```
TypeError: api.on.editInspectorState is not a function
```
```
TypeError: api.on.visitComponentTree is not a function
```

**Comment by Akryum** [comment]
Please use the issue helper. https://new-issue.vuejs.org/?repo=vuejs/vue-devtools

**Comment by prog-rajkamal** [comment]
It is because firefox gas devtools v5. Only devtools V6(currently in beta) supports Vue3

**Comment by ErickTucto** [comment]
Version beta https://github.com/vuejs/devtools/releases
