### ISSUE TITLE
Vue.js not detected in production mode

### ISSUE THREAD

**Issue by qzmlgfj** [vuejs/devtools#1534]
### Version
6.0.0-beta.15

### Browser and OS info
Chrome 92/Windows 10

### Steps to reproduce
Build the project with `vue-cli-service build`, and deploy it on local Nginx, the App worked as expected, but Vue devtools tells that Vue.js is not detected.

### What is expected?
Vue.js is detected on this page.

### What is actually happening?
Vue.js not detected

---
Everything is normal in development mode, even if I create a new project, the problem still occurs.

I know devtools inspection is not available in production mode, but at least the extension icon will light when comes to a website based on Vue.js, but this doesn't work for me.

**Comment by codetheorist** [comment]
Could you possibly setup a repro of it, a test URL or provide a little more information with regards to your config?

**Comment by qzmlgfj** [comment]
Just use Vue CLI to create a default Vue3 project, build it and deploy on a local Nginx or Live server.

And I found a prompt on this [page](https://devtools.vuejs.org/guide/faq.html#the-vue-devtools-don-t-show-up), which says:

>If you are on a live website, there is a good chance it's using a production build of Vue.

But this won't happen on a Vue2 website, and I'm confused about that.

**Comment by Akryum** [comment]
Please read a little bit more text on the documentation page you linked yourself :cat2:

**Comment by qzmlgfj** [comment]
Do you mean set `__VUE_PROD_DEVTOOLS__` environment variable? 

If so, Vue CLI has already done that.

If not, please tell me which part you refer to.

**Comment by Akryum** [comment]
> Do you mean set `__VUE_PROD_DEVTOOLS__` environment variable?

Yes.

**Comment by qzmlgfj** [comment]
Using `vue-cli-service inspect`, the output shows CLI has set the environment variable like this:

```javascript
/* config.plugin('feature-flags') */
new DefinePlugin(
      {
        __VUE_OPTIONS_API__: 'true',
        __VUE_PROD_DEVTOOLS__: 'false'
      }
    )
```

But the devtools still told me `Vue.js not detected` after deploying it.

This doesn't affect production build, but when I come across other websites based on Vue3 and devtools detects Vue.js, I still wonder why it works at this time.

**Comment by Akryum** [comment]
You need to set it to `true` to enable devtools support in production.

**Comment by qzmlgfj** [comment]
Devtools has three statuses:

* Vue.js not detected
* Vue.js is detected but devtools inspection is not available
* Vue.js is detected and devtools inspection is available

I know devtools inspection is not available in production mode, and I don't need it until now.

Unfortunately, I haven't found a way to change `__VUE_PROD_DEVTOOLS__` in CLI yet, but I guess your advice makes devtools inspection available.

However, in this issue, I just want the icon of devtools to light up.

**Comment by Akryum** [comment]
Without a link or a reproduction I can't help you further.

**Comment by qzmlgfj** [comment]
I just created a default Vue3 project again, and found the issue disappeared.

I compared it with my old project, trying to find the reason but failed.

Still, I'm happy to see that this issue doesn't happen in a project created last month, but I didn't notice at that time.

Sorry for wasting you guys' time.
