### ISSUE TITLE
Collapse all properties

### ISSUE THREAD

**Issue by debug87** [vuejs/devtools#1543]
Why are all (or some) properties always expanded? It is incredibly annoying when everything is expanded every time and you have to collapse it to get a clear view.
All properties (data, props, etc.) should always be collapsed.

**Comment by piotrmachacki** [comment]
Please fix this because it's currently hard to use when everything is expanded.

**Comment by konpeki622** [comment]
For collapse all properties, press `ctrl` or `meta` on keyboard while clicking the toggle. For expand press `shift` instead.

**Comment by Akryum** [comment]
Duplicate of #1391
