### ISSUE TITLE
Being able to disable Component Events (or any other timeline)

### ISSUE THREAD

**Issue by posva** [vuejs/devtools#1545]
Some components emit too many events and make it difficult to inspect the timeline. It would be nice if, in v6, it was possible to disable any of the timelines like we can with the performance one, right from the timeline:

<img width="583" alt="Screenshot 2021-08-23 at 15 21 51" src="https://user-images.githubusercontent.com/664177/130454558-a4c76506-e3c8-4d11-b790-66f94206e98d.png">

One of the most common examples is applications using map components. They emit a lot of events and it becomes laggy quite quickly (after moving the map around, the timeline can take up to +30s to charge), making it hard to debug any other timeline.

This was possible in v5 with the small record button, to stop tracking component events.

**Comment by Akryum** [comment]
Did you try hiding the layer? Is it still taking a performance hit?

**Comment by posva** [comment]
I completely forgot you could hide them! It reduces the time a bit but it still takes about 10s to load.

**Comment by Akryum** [comment]
Maybe the improvement would be to prevent sending the events over the wire when the layer isn't visible and then fetch the layer again when it's toggled

**Comment by posva** [comment]
I would say that completely dropping the events to avoid any memory increase could be better.

I still think having a button directly on the timeline is more intuitive than the list button to toggle. I always forget it exists!
