### ISSUE TITLE
async method and Data object

### ISSUE THREAD

**Issue by Timoffey** [vuejs/devtools#1548]
### Version
6.0.0-beta.15

### Browser and OS info
MacOS 10.14.6 Chrome 92.0.4515.159

### Steps to reproduce
I used an async function. In async function Ichange my data object. And vue-devtools doesn't changed. But data object is correctly changed.
0) open vue-devtools and look to your dataobject
1) crerate async method with fetch 
2) get response from fetch
3) set data object equal to response.json()
3.5) you can console.log your data object and it will be ok
4) look to vue-devtools – data object is unchanged

### What is expected?
data object in dev-tools will be changed

### What is actually happening?
data object in dev-tools unchanged

**Comment by Akryum** [comment]
Please provide a runnable reproduction, thanks!
