### ISSUE TITLE
Capability of copying the component name

### ISSUE THREAD

**Issue by Daniel4Digital** [vuejs/devtools#1555]
After clicking on a component, on the right side we can see the props, data, computed, and on that side on the top we've the Components Name and a field to filter inspected data.

If we click on components name nothing happen at the moment, it could copy the component name. Would be very handy.

best regards

**Comment by jacekkarczmarczyk** [comment]
Copying should be also possible from the bottom panel, there's a possibility to select the component name, but Ctrl-C doesn't work

![image](https://user-images.githubusercontent.com/15625235/152056723-646e449c-a0cc-44f0-91d9-0fb4f581c64f.png)

**Comment by Akryum** [comment]
@jacekkarczmarczyk I just tried copying the component with success. Could you try again?

**Comment by jacekkarczmarczyk** [comment]
it doesn't work for me, 6.0.12, tried to copy some content from the website to make sure ctrl-c works
i can copy component name from the menu, but not with ctrl-c combination
