### ISSUE TITLE
Cannot click components within component tab in order to see component state

### ISSUE THREAD

**Issue by eddie0329** [vuejs/devtools#1558]
### Version
6.0.0-beta.16

### Browser and OS info
ios

### Steps to reproduce
1. Click Component Tab
2. Click Component (🐛 cannot able to see state. only blinks)

### What is expected?
View component state

### What is actually happening?
cannot able to see component state

**Comment by Akryum** [comment]
Please provide an actual reproduction. There is not enough information to do anything.

> ### Browser and OS info
> 
> ios

The Vue Devtools can't be installed on iOS :thinking:
