### ISSUE TITLE
Component Inspector not expanding some components

### ISSUE THREAD

**Issue by scp-nm** [vuejs/devtools#1560]
### Version
6.0.0-beta.17

### Browser and OS info
Chrome 93 / MacOS 11.5.2

### Steps to reproduce
Launch app (in none production build) running Vue 2.6.14
Open Chrome DevTools panel
Click Vue tab
Note load time of Vue.js DevTools plugin is increased from `beta.15`
Note there may be some components that are not expandable in the Component Inspector list
---
I will try to include some context to this bug, as a re-produceable repo is difficult to provide given the size and complexity of the project I'm experiencing this issue with.

We have a fairly large SaaS platform that runs on Vue 2.6.14, along with Vuex 3.6.2, Vue Router 3.5.2 and the UI framework is being provided using Vuetify 1.5.24.

For a long while (prior to `beta.15` the only reliable experience I've been able to get is to use Firefox with the v5 version of Vue.js DevTools extension (Chrome with the same version of the DevTools extension would simply bomb out).

When `beta.15` of v6 came out (with support for Vue.js v2) I was pleased to be able to use Vue.js DevTools in Chrome regularly with no performance issues, and I can honestly say it was a great experience again, so thanks for this.

However, when launching Chrome with the `beta.17` version of Vue.js DevTools this morning I can report that for some reason the performance (load-time) has probably doubled, and also I'm experiencing that some components are not expandable in the Component Inspector. This makes the Launch in Editor feature useless for any components nested within the non-expandable component.

The particular component that isn't expandable happens to be `v-content` component of Vuetify v1.5.x. As a result that makes the majority of the nested components properly un-inspectable.

I will try to reproduce this with a simplified `codesandbox` example when I get the chance.

### What is expected?
All components in the Component Inspector are expandable

### What is actually happening?
Certain components are not expandable

**Comment by chris-garner** [comment]
Same as https://github.com/vuejs/devtools/issues/1563

**Comment by scp-nm** [comment]
This issue has since mutated (?), now the component that I couldn't previously expand is simply not displayed in the Component Inspector. This is using `beta.18`.

There's also an additional warning in the console:

> DevTools failed to load source map: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/fast-copy.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by scp-nm** [comment]
@Akryum I've finally managed to get a [repo](https://codesandbox.io/s/report-cards-grid-6wk0s) where the problem is happening.

When DevTools (`v6.0.0-beta.18`) is open, go to Component Inspector and expand:

`<Root>  >  <app>  >  <v-app>  >  <v-content>  >  <PageDashboard>  >  <PageWrapper>`

You'll see that `<PageWrapper>` can't expand further. I hope this helps.

**Comment by scp-nm** [comment]
Just wanted to say thanks @Akryum - I'm able to use `beta.19` quite reliably in Chrome. Will feedback separately if I come across anything else.
