### ISSUE TITLE
`console.log` leftover in processProps function

### ISSUE THREAD

**Issue by bgoscinski** [vuejs/devtools#1567]
### Version
6.0.0-beta.18

### Browser and OS info
any

### Steps to reproduce
open devtools, inspect console

### What is expected?
devtools extension doesn't pollute the console

### What is actually happening?
devtools extension pollutes the console

---
This one https://github.com/vuejs/devtools/blob/6ab078a1c863016f4fea990fdfa565c5318084bc/packages/app-backend-vue3/src/components/data.ts#L47 was introduced while fixing https://github.com/vuejs/devtools/issues/1559

**Comment by Grawl** [comment]
i hope update will be ready until monday
