### ISSUE TITLE
The Chrome beta devtools plugin needed for Vue 3 development is blocked by our corporate security team

### ISSUE THREAD

**Issue by DVMVCGCG** [vuejs/devtools#1570]
### What problem does this feature solve?
The stated reason is:

> Grants Critical Permission to <all_urls> Matches any URL that uses a permitted scheme, which combined with local storage permission, may lead to Extension being used to spy on browsing activity

The Vue 2 devtools passes all the security checks. Is there any plan to stop requiring the `<all_urls>` permission?

### What does the proposed API look like?
Since the Vue 2 devtools is able to function without `<all_urls>`, I assume the same should be possible for Vue 3.

**Comment by Akryum** [comment]
I'm afraid we need this permission. All vue-devtools versions have always required access to all urls. We just change it to `<all_urls>` which is much cleaner.

https://github.com/vuejs/devtools/blob/80924e596eb8cd018ed1bc5a4b0c5cd734f071ed/packages/shell-chrome/manifest.json#L34

I guess your corporate checks aren't that good. 😹
