### ISSUE TITLE
suspense tag was not shown on fallback component

### ISSUE THREAD

**Issue by konpeki622** [vuejs/devtools#1592]
### Version
6.0.0-beta 19

### Browser and OS info
Chrome 93.0.4577.63, Windows 10

### Steps to reproduce
Init a project with vue 3.x and add component `Loading` as suspense fallback.

### What is expected?
Suspense tag was shown on component `Loading`.

### What is actually happening?
Tag was not shown.
![suspense](https://user-images.githubusercontent.com/28253544/139039534-da429ebf-d023-45a2-8bc1-b1c3009f77a6.PNG)

**Comment by Akryum** [comment]
Closed in https://github.com/vuejs/devtools/commit/ce30047a945fb23b3062440edee18c0fe7a11d86
