### ISSUE TITLE
vue-devtools无法和vuex-persistedstate插件很好的工作

### ISSUE THREAD

**Issue by Sc-6-23** [vuejs/devtools#1597]
### Version
6.0.0-beta.19

### Browser and OS info
Edge 95.0.1020.40 / Windows 10

### Steps to reproduce
在vuex中使用vuex-persistedstate将数据保存在sessionStorage, 页面刷新后在vue-devtools中无法看到vuex里的数据

### What is expected?
页面刷新后能在vue-devtools看到vuex中使用vuex-persistedstate保存到sessionStorage中的数据

### What is actually happening?
页面刷新后在vue-devtools中无法看到vuex中使用vuex-persistedstate保存到sessionStorage中的数据

**Comment by codetheorist** [comment]
Possible duplicate https://github.com/vuejs/devtools/issues/1547

**Comment by Akryum** [comment]
Duplicate of [#1547 ](https://github.com/vuejs/vuex/issues/2046)
