### ISSUE TITLE
vue 赋值出现影响原数组

### ISSUE THREAD

**Issue by yzx274221768** [vuejs/devtools#1619]
vue 版本 https://cdn.jsdelivr.net/npm/vue@2

// 没有赋值的时候
![image](https://user-images.githubusercontent.com/43923759/143515644-9f2c4780-1735-4390-911b-9909598c354c.png)
// 控制台输出
![image](https://user-images.githubusercontent.com/43923759/143515737-a88fecb0-7791-439f-ac3e-f579b1a50190.png)

// 赋值操作
![image](https://user-images.githubusercontent.com/43923759/143515903-1ca3b7a8-62cb-4892-b5ce-47e06eedfc40.png)
// 赋值以后 控制台输入 
![image](https://user-images.githubusercontent.com/43923759/143515903-1ca3b7a8-62cb-4892-b5ce-47e06eedfc40.png)

赋值以后 控制台可以看到 数组length为0，但是遍历还是可以遍历

**Comment by yzx274221768** [comment]
// 赋值操作
![image](https://user-images.githubusercontent.com/43923759/143516067-7c5d48c2-f00e-4667-aaaf-e7c546837a7e.png)

**Comment by Akryum** [comment]
Hi! Please use [the issue helper](https://new-issue.vuejs.org/?repo=vuejs/vue-devtools) when creating issues. Thanks!
