### ISSUE TITLE
computed will auto run by devtools

### ISSUE THREAD

**Issue by zhangenming** [vuejs/devtools#1627]
### Version
6.0.0-beta.20

### Browser and OS info
chrome 92 / windows 10

### Steps to reproduce
```vue
<script setup>
  import { computed, ref } from 'vue'
  const r = ref(0)
  const r2 = ref(0)
  const c = computed(() => {
    r2.value++
    return r.value
  })
</script>
<template>r2 = {{ r2 }}</template>
```

### What is expected?
r2 = 0

### What is actually happening?
r2 = 1

**Comment by Akryum** [comment]
Don't put side-effects in computed properties.
