### ISSUE TITLE
Remote Devtools Vue 3 Detection

### ISSUE THREAD

**Issue by OyewoleOyedeji** [vuejs/devtools#1636]
After installing the electron app with

`npm install -g @vue/devtools`

It works perfectly well for version 2, but not for version 3 (it doesn't detect it at all). I installed it, thinking it would be better than the `Vue.js Devtools Beta` extension. I need it for debugging `vuex` stores

If needed,
Use Windows 10
Vue 3 version - 3.2.26

I started the Vue serve from the `Vue Project Manager`

**Comment by akkayy** [comment]
Try:

npm install -g @vue/devtools@6.0.0-beta.20
