### ISSUE TITLE
Electron app not detecting Vue 3

### ISSUE THREAD

**Issue by OyewoleOyedeji** [vuejs/devtools#1639]
### Version
5.3.4

### Browser and OS info
Microsoft Edge 95 / Windows 10

### Steps to reproduce
1. I setup a project with `@vue/cli` with a Vue 3
2. `npm install -g @vue/devtools`.
3. I started vue-devtools, and added `<script src="http://localhost:8098"></script>` to my project
4. I wait for it to sync to the project

### What is expected?
For the components, routes, events, and state to show up like, it does for Vue 2

### What is actually happening?
Nothing happens it just gives me a blank page 

---
I thought this will be a better alternative to the `Vue.js beta` browser extension for Chrome

**Comment by Akryum** [comment]
v5 doesn't support Vue 3, please use v6

**Comment by OyewoleOyedeji** [comment]
@Akryum how do I use version v6

**Comment by Akryum** [comment]
You have all the info you need on npm:

https://www.npmjs.com/package/@vue/devtools

![image](https://user-images.githubusercontent.com/2798204/146548985-b745ac94-381e-4106-a6ee-5f533b08619b.png)

There is version 6 that you can install either with `@vue/devtools@^6 ` or `@vue/devtools@beta`

**Comment by OyewoleOyedeji** [comment]
Thanks
