### ISSUE TITLE
Better explain how to setup plugin in Vue 2 app

### ISSUE THREAD

**Issue by Kasheftin** [vuejs/devtools#1667]
### Version
6.0.0-beta.21

### Browser and OS info
Chrome 97 / Ubuntu 21

### Steps to reproduce
1. vue create test1 (all options default, vue2 app)
2. npm i --save @vue/devtools-api
3. add 2 files from docs:
````
// devtools.js

import { setupDevtoolsPlugin } from '@vue/devtools-api'

export function setupDevtools (app) {
  console.log('setup devtools plugin for', app)
  setupDevtoolsPlugin({
    id: 'grouped-logs',
    label: 'Grouped Logs',
    app,
    settings: {
      test1: {
        label: 'I like vue devtools',
        type: 'boolean',
        defaultValue: true
      }
    }
  }, (api) => {
    console.log(api, api.getSettings())
    api.on.setPluginSettings((payload) => {
      console.log('setting changed to', payload)
    })
  })
}

// DevtoolsPlugin.js
import { setupDevtools } from './devtools'

export default {
  install (app) {
    setupDevtools(app)
  }
}
````
4. Add Vue.use(DevtoolsPlugin) to main.js file.

Docs says that's all that required to see the custom plugin in vue-devtools. Do I miss something? The devtools plugins section shows only one plugin (Vue2).

![Screenshot from 2022-01-17 17-48-58](https://user-images.githubusercontent.com/379267/149804266-9417796d-d7cc-44ab-8330-f920d924b54c.png)

### What is expected?
there should be my custom plugin in the list of devtools plugins

### What is actually happening?
no my custom plugin in the plugins list of devtools

---
It would be really helpful if there's a sample hello-world application with any hello world plugin connected and called from inside the app.

https://github.com/Kasheftin/hello-world-vue-devtools-plugin

**Comment by Akryum** [comment]
In a Vue 2 app, you need to pass the root component as the `app`.

**Comment by Akryum** [comment]
```js
import Vue from 'vue'
import App from './App.vue'
import DevtoolsPlugin from './DevtoolsPlugin'

Vue.config.productionTip = false
Vue.use(DevtoolsPlugin)

new Vue({
  render: h => h(App),
  myPlugin: true,
}).$mount('#app')
```

```js
import { setupDevtools } from './devtools'

export default {
  install (Vue) {
    Vue.mixin({
      beforeCreate () {
        if (this.$options.myPlugin) {
          setupDevtools(this)
        }
      }
    })
  }
}
```

**Comment by Akryum** [comment]
https://github.com/Akryum/vue2-devtools-plugin-example
