### ISSUE TITLE
Inspection not available when running locally

### ISSUE THREAD

**Issue by dwschulze** [vuejs/devtools#1672]
### Version
6.0.0-beta.21

### Browser and OS info
Edge  97.0.1072.69 (Official build) (64-bit) and Chrome 97.0.4692.99 (Official Build) (64-bit)  on Ubuntu 20.04

### Steps to reproduce
Run my vue app locally
Open dev console
Vue icon shows 

Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

I have

app.config.devTools = true;

in main.js

### What is expected?
Devtools should show Vue option

### What is actually happening?
No vue support

**Comment by LeoDupont** [comment]
Same problem running `vue-cli-service serve --mode development`.
Logging `process.env.NODE_ENV` prints "development".
The app seems to be running in development mode and I haven't explicitly disabled Devtools inspection.

I'm using Vue 3, Vuex and Vue Router. Could it be the issue?

**Comment by Akryum** [comment]
Please provide a minimal runnable reproduction. Thanks

**Comment by dwschulze** [comment]
Vue tools finally started working again after I did a yarn install on the project.
