### ISSUE TITLE
No state displayed in namespaced vuex module

### ISSUE THREAD

**Issue by Silver-IT** [vuejs/devtools#1680]
### Version
6.0.1

#### Environment
Firefox 96.0.3 on Ubuntu OS

#### Condition
Working on Vue.js v2 having Vuex store with several namespaced stores in it.

### What is expected?
Wanted to inspect states and getters of all the nested namespaced stores as well as the root Vuex store.

### What is actually happening?
I can inspect the root state and all the getters(from the root and the namespaced ones)
But I can not inspect the states of namespaced Vuex stores.

---
**Screenshot 1**
![image](https://user-images.githubusercontent.com/57976479/152912725-8b124dc1-5284-4bd0-9b1e-d1b8c7277c3a.png)
**Screenshot 2**
![image](https://user-images.githubusercontent.com/57976479/152913058-0b9c9cff-68ac-43b3-a190-6645d1144c33.png)

**Comment by Silver-IT** [comment]
Sorry. there is a typo. `should be displayed` not `should be displaced`.

**Comment by Akryum** [comment]
Please provide a runnable reproduction of your issue otherwise we can't fix it.

Here is what I get in a real app:
![image](https://user-images.githubusercontent.com/2798204/152962176-3030adf8-e7c6-4655-bdff-0d1a22980cb2.png)

**Comment by weeliem** [comment]
Vuex in devtool is not updated after state changed.

**Comment by Silver-IT** [comment]
> Please provide a runnable reproduction of your issue otherwise we can't fix it.
> 
> Here is what I get in a real app: ![image](https://user-images.githubusercontent.com/2798204/152962176-3030adf8-e7c6-4655-bdff-0d1a22980cb2.png)

Is it in Firefox browser? And version 6.0.1?
On my side, I can see two errors when click `Vue.js dev tools`.
![image](https://user-images.githubusercontent.com/57976479/153153686-0f2a72ee-8605-4b01-9faa-350030d69fab.png)

**Comment by weeliem** [comment]
I am using Google Chrome Version 98.0.4758.81. Actually you may refer to issue #1675 .

**Comment by lateshift** [comment]
> Vuex in devtool is not updated after state changed.

Yupp same for me (Vue 2.6.11, Vuex 3.4.0, Extension: v6.0.2, Latest stable FireFox). Changes to the store aren't displayed in the state tree (not using namespaces!).

**Comment by Akryum** [comment]
@Silver-IT Please provide a runnable reproduction of your issue otherwise we can't fix it.

**Comment by nathanvision** [comment]
same problem here.

Nuxt 2.14.12
Vue 2 2.6.12
Vue.js devtools 6.0.0

I use namespace module for the store.
States have default value (empty array, null, ...) but the getters have data.
No error in console. Project work like a charm. It's just we can't see the content of the states.

**Comment by djames-rms** [comment]
Same problem here. Namespaced stores are not updating from init state.

Is there any way to revert back to a previous version?

**Comment by ejs7rh19** [comment]
You can also view the store from here:
![image](https://user-images.githubusercontent.com/45642063/153289949-7533841d-0828-493c-b2d1-166337c790cb.png)

**Comment by djames-rms** [comment]
> You can also view the store from here: ![image](https://user-images.githubusercontent.com/45642063/153289949-7533841d-0828-493c-b2d1-166337c790cb.png)

Sure, but this feels like hack when you can't remove any of the timeline columns. The inspector view should show current/updated state for vuex modules, IMO.

**Comment by volkov-aleksandr** [comment]
![image](https://user-images.githubusercontent.com/84247924/153373300-0462202c-bd98-4b6d-8c7a-b1641a8bb59d.png)
Same problem. State has default values, but getters work.

**Comment by Akryum** [comment]
> **Screenshot 1** ![image](https://user-images.githubusercontent.com/57976479/152912725-8b124dc1-5284-4bd0-9b1e-d1b8c7277c3a.png) **Screenshot 2** ![image](https://user-images.githubusercontent.com/57976479/152913058-0b9c9cff-68ac-43b3-a190-6645d1144c33.png)

Looking at your screenshot, looks like the state is folded. Did you try unfolding it?
