### ISSUE TITLE
Vuex edit state 

### ISSUE THREAD

**Issue by KVAnton-WEB** [vuejs/devtools#1683]
### Version
6.0.1

### Reproduction link
[github.com](https://github.com/KVAnton-WEB/vuex_playground)

### Steps to reproduce
open devtools and try to change vuex state (test) and save it.

### What is expected?
change state

### What is actually happening?
Can't edit Vuex state, when changing value and saving – data doesn't change

---
Vue 2.6.14
Firefox 96.0
Ubuntu 20.04

**Comment by Akryum** [comment]
My mistake to let editing enabled. It's not implemented yet and I overlooked this for the v6 release.
