### ISSUE TITLE
getInspectorState / mixed namespaced modules between tabs

### ISSUE THREAD

**Issue by t-tomek** [vuejs/devtools#1684]
### Version
6.0.1

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/brave-torvalds-77crm?file=/src/main.js)

### Steps to reproduce
Create namespaced store with some modules (can be empty). Having another vue instance in other tab leads to errors. It looks like current tab has data of previously opened tab.

### What is expected?
To work ;)

### What is actually happening?
Many errors like that:

An error occurred in hook getInspectorState registered by plugin org.vuejs.vue2-internal

---
At first I couldn't get to work a project & new vue-devtool plugin I've started yesterday (it used to work with old plugin). Today after update I got many "An error occurred in hook getInspectorState registered by plugin org.vuejs.vue2-internal" errors.

What's important it seems that there's a problem with Vuex namespaces and tab context. I don't have path "ns/otherNs/ in the project but when I created bug example and reloaded my project's page i saw this error: Missing module "ns" for path "ns/otherNs/" which is quite imposible becouse there's no such namespace in my project as it only exists in example.

**Comment by t-tomek** [comment]
![obraz](https://user-images.githubusercontent.com/8792897/152984751-b7e8c6e0-5208-4161-8602-5cfb59ed34d4.png)
And the other way round. I reloaded example page and got error about not existing namespace orderBox which... is created in other browser's tab - not in example tab.

**Comment by Akryum** [comment]
Interesting issue :eyes: 
Is it also misbehaving in other parts of the devtools such as the components inspector and the timeline?

**Comment by t-tomek** [comment]
I didn't notice that. It all worked until I tried to check vuex state.

**Comment by t-tomek** [comment]
Looks like archaic Vuex version (3.0.1....) caused all the problems. 

With 3.6.2 all works like a harm :)
