### ISSUE TITLE
sub is not a function error if vuex dispatch is calling

### ISSUE THREAD

**Issue by reznik789** [vuejs/devtools#1686]
### Version
6.0.2

### Reproduction link
https://codesandbox.io/s/535kx57jpx

### Steps to reproduce
Open vue tab in devtools. Call vuex dispatch method

### What is expected?
dispatch method works as usual

### What is actually happening?
The method throws an error
Uncaught (in promise) TypeError: sub is not a function

---
Vue version: 2.5.22. Browsers: Firefox and Chrome. OS: Ubuntu

**Comment by Akryum** [comment]
Vuex 3.0.0 and 3.0.1 are not currently supported by the devtools. Try upgrading to at least Vuex 3.1.
https://codesandbox.io/s/vuex-store-forked-i772y?file=/package.json

**Comment by nickpapageo** [comment]
@Akryum is there any plan to fix this bug in Vuex 3.0.0 and 3.0.1? I have the same issue with Vuex 3.0.1

**Comment by Akryum** [comment]
Since it's impossible to detect if the vuex version is below 3.1.0, I added a setting in the Vue 2 builtin plugin:

![image](https://user-images.githubusercontent.com/2798204/153394990-62376d5d-b062-4f30-be0f-6354a05f25b4.png)

**Comment by Bosphoramus** [comment]
It is weird that devtools incompatibility breaks your app.

I would understand that the devtools wont work properly when they have to detect old vue versions, but i dont get why your app should break just because of that

**Comment by Akryum** [comment]
Only very old versions of vuex break (prior to Vuex 3.1.0).

**Comment by Bosphoramus** [comment]
Thanks for the explanation @Akryum

**Comment by edwardcxyz** [comment]
Just in case anyone else runs into this issue and finds this thread, like I did...

If you are using Vue 2, the current version of Vue Devtools for Chrome breaks with the `sub is not a function` error.  To resolve the issue, uninstall it the current Vue Devtools and install the [LEGACY Vue Devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp) extension instead.

**Comment by Akryum** [comment]
@edwardcxyz  You need to toggle the 'Legacy Actions' in the Vue 2 plugin settings, see https://github.com/vuejs/devtools/issues/1686#issuecomment-1034789116

**Comment by FourSeventy** [comment]
Typical f*&$ing javascript. Unreal. When the dev tools break your app you know something has gone seriously wrong with the toolchain

**Comment by FourSeventy** [comment]
This is a freaking joke right? How can JS even begin to take itself seriously when nonsense like this occurs.

**Comment by MaikeMota** [comment]
> Just in case anyone else runs into this issue and finds this thread, like I did...
> 
> If you are using Vue 2, the current version of Vue Devtools for Chrome breaks with the `sub is not a function` error. To resolve the issue, uninstall the current Vue Devtools and install the [LEGACY Vue Devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp) extension instead.


Still having the same problem with the LEGACY version, but I found and tried the v5 and works fine for me now.

Heres the extension link for chrome in case anyone else needs that: [vuejs-devtools-v5](https://chromewebstore.google.com/detail/vuejs-devtools-v5/hkddcnbhifppgmfgflgaelippbigjpjo)

**Comment by MaikeMota** [comment]
> Just in case anyone else runs into this issue and finds this thread, like I did...
> 
> If you are using Vue 2, the current version of Vue Devtools for Chrome breaks with the `sub is not a function` error. To resolve the issue, uninstall the current Vue Devtools and install the [LEGACY Vue Devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp) extension instead.

Still having the same problem with the LEGACY version, but I found and tried the v5 and works fine for me now.
Heres the extension link for chrome in case anyone else needs [vuejs-devtools-v5](https://chromewebstore.google.com/detail/vuejs-devtools-v5/hkddcnbhifppgmfgflgaelippbigjpjo)
