### ISSUE TITLE
Vue2 fails when using a VueComponent instead of Vue as root

### ISSUE THREAD

**Issue by 0Rick0** [vuejs/devtools#1687]
### Version
6.0.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/gracious-hooks-oicom)

### Steps to reproduce
Use Vue 2
Create a component using `Vue.extend()`
Create an instance of the component using `new` and mount it on the page.
Open Vue dev tools.

### What is expected?
The component can be inspected using Vue dev tools

### What is actually happening?
An exception is thrown
```javascript
Uncaught (in promise) TypeError: options.version is undefined
    registerAppJob backend.js:949
...
```

---
The root cause seems to be in this function.
https://github.com/vuejs/devtools/blob/b3dd744c6ec3a4eeb200b8003e0ff74b9e78abfe/packages/app-backend-core/src/app.ts#L235

In some cases (e.g. `Vue.extend`) `app.constructor` points to `VueComponent` instead of `Vue`. This class does not have a version property.

**Comment by 0Rick0** [comment]
I think this can be solved by wrapping the Vue constructor retrieval with a function like this:
```javascript
function getVueInstance(app) {
    if (app.constructor.name === 'VueComponent') {
        return app.constructor.super;
    }
    return app.constructor;
}
```
Let me know if this is correct, then I will create a PR for this!
Not sure if this logic is also required in other locations.

**Comment by Akryum** [comment]
@0Rick0 looks like a good idea to me!
