### ISSUE TITLE
 Cannot read properties of undefined (reading 'substr')  - backend.js:949:57

### ISSUE THREAD

**Issue by polPintero** [vuejs/devtools#1689]
### Version
6.0.0

### Reproduction link
[http://localhost:8881/](http://localhost:8881/)
Error in this line:
 const baseFrameworkVersion = parseInt(options.version.substr(0, options.version.indexOf('.')));

### Steps to reproduce
Vue 2. Open vue-devtools in chrome

### What is expected?
no error

### What is actually happening?
error

**Comment by Akryum** [comment]
Duplicate of #1687
