### ISSUE TITLE
Latest devtools 6.0.2 not listed in chrome web store - still 6.0.0 installed

### ISSUE THREAD

**Issue by lorand-horvath** [vuejs/devtools#1693]
### Version
6.0.2

### Reproduction link
[chrome.google.com](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)

### Steps to reproduce
The latest vue devtools 6.0.2 is not listed in the chrome web store, which still shows 6.0.0 https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd
My Chrome browser installed 6.0.0 and won't go above that.
On the other hand, Firefox installs 6.0.2, as expected.

### What is expected?
Latest devtools 6.0.2 should be listed and installed in the browser.

### What is actually happening?
An older version is installed 6.0.0.

**Comment by Akryum** [comment]
Google takes forever to validate extension updates. Chrome will always lag behind Firefox release.

**Comment by lorand-horvath** [comment]
@Akryum Not sure that's the issue. It looks more like the chrome web store publishes the **previous** version as soon as you push the latest one. Now it published 6.0.2 on the exact same day when the latest 6.0.5 was released on github. Anyway...

**Comment by Akryum** [comment]
That's the issue. I know, I'm the one uploading the versions to the Chrome Web Store :sweat_smile:
