### ISSUE TITLE
vuedevtools新版 看不到uniapp h5页面的值

### ISSUE THREAD

**Issue by a774968215** [vuejs/devtools#1699]
### Version
6.0.5

### Browser and OS info
Chrome 98 / Windows10

### Steps to reproduce
打开uniapp h5 页面 用vuetools 选中页面 看不到页面存储的值  vuedevtools 没升级之前可以看到

### What is expected?
希望可以看到页面数据

### What is actually happening?
希望可以看到页面数据

---
希望可以看到页面数据

**Comment by best-fan** [comment]
蹲一下

**Comment by Akryum** [comment]
Please provide a runnable reproduction. Thanks :pray:

**Comment by lioilLRM** [comment]
same problem.
I have uploaded an attachment，need HbuilderX code editor run it.

HbuilderX download url:https://www.dcloud.io/hbuilderx.html

[helloUniapp.zip](https://github.com/vuejs/devtools/files/8046193/helloUniapp.zip)
![image](https://user-images.githubusercontent.com/26706629/153543986-dd0957ea-c73b-4f2c-ba3c-47647a862d21.png)


![image](https://user-images.githubusercontent.com/26706629/153543664-4e527923-d921-43b3-959e-891fbe5c4781.png)

**Comment by Nxir** [comment]
same problem

**Comment by shadow7en** [comment]
same problem

**Comment by zeekrs** [comment]
same problem

**Comment by Akryum** [comment]
Not reproducing on 6.0.6
<img width="1677" alt="Screenshot 2022-02-11 at 13 36 46" src="https://user-images.githubusercontent.com/2798204/153592592-19f03599-943d-43c7-87a7-6019bf188356.png">

**Comment by lioilLRM** [comment]
> Not reproducing on `main`branch. The issue was probably resolved by other fixes. <img alt="Screenshot 2022-02-11 at 13 36 46" width="1677" src="https://user-images.githubusercontent.com/2798204/153592592-19f03599-943d-43c7-87a7-6019bf188356.png">

Is this component, have some data in Vue2.x

![image](https://user-images.githubusercontent.com/26706629/153609409-ce4a3f6a-ec19-4d99-be11-91e85c9d3d7b.png)

this is code
![image](https://user-images.githubusercontent.com/26706629/153609763-3fa7ce51-84cd-41b9-a2e8-11c9d4c214c3.png)
@Akryum

**Comment by lioilLRM** [comment]
Hi, @Akryum I found that you have updated some code, you are great.
So I  update Vue.js devtools to newest version 6.0.6
but I can't inspect data for child components.

![image](https://user-images.githubusercontent.com/26706629/153700461-4c339667-56e4-4f03-9a37-8118cd8f497c.png)

![image](https://user-images.githubusercontent.com/26706629/153700545-a1957e15-35ea-4fe1-b36a-62b26b0f8652.png)

**Comment by Akryum** [comment]
It takes a few days for Google to publish extension updates to Chrome. Meanwhile, you can try on Firefox (it gets updates in a few minutes after I upload them) or [build the extension yourself](https://devtools.vuejs.org/guide/contributing.html).

**Comment by lioilLRM** [comment]
Thank! I test project in Firefox use newest version 6.0.8 vue.js devtools.
It work great

**Comment by ylc6223** [comment]
the same problem. I test project in chrome use newest version 6.1.4 vue.js devtools.
It  doesn't  work
