### ISSUE TITLE
Devtools not work when use  $mount  append custom Component (> Version 6)

### ISSUE THREAD

**Issue by gavinwyf** [vuejs/devtools#1708]
Version: 6.0.2 
Vue2 Component

**Comment by defghy** [comment]
same problem

`
const instance = new Vue.extend({...})({
        propsData: {...},
});

document.body.appendChild(instance.$mount().$el);
`
6.0.*
![image](https://user-images.githubusercontent.com/5386958/153559543-1bc8febb-0970-472a-8674-233d20478682.png)

5.3.4
![image](https://user-images.githubusercontent.com/5386958/153559696-a5af2398-666d-4559-99f5-725c11e88d64.png)
