### ISSUE TITLE
Vuex store Root not working in Firefox 97

### ISSUE THREAD

**Issue by corvinsoft-fauszta** [vuejs/devtools#1713]
### Version
6.0.6

### Browser and OS info
Firefox 97 / Windows 10

### Steps to reproduce
* Create a simple Vuex store with elements in the root state

```js
import Vuex from 'vuex'
Vue.use(Vuex)

const store = new Vuex.Store({
  state:{
    user:"user"
  }
});

const app = new Vue({
  el: '#app',
  store,
})
```

* Open the Vue Devtools
* Navigate to Vuex
* Select Root

### What is expected?
The stored key is visible under the Root

### What is actually happening?
The Root is empty

---
If I include modules they work correctly, the issue is only with the Root element.

~~The DevTool is working fine in Chrome 98~~

Edit: Downgrading to 6.0.5 solved the issue

Edit 2: I discovered in Chrome I run 6.0.2 so that part is irrelevant

**Comment by traxium** [comment]
I still have the same issue on Vue.js devtools 6.1.4. But it works as expected on Vue.js devtools 5.3.4.
