### ISSUE TITLE
Vuex state not updating in Vue devtools, showing always the initial store state.

### ISSUE THREAD

**Issue by Hendersonpinto** [vuejs/devtools#1715]
### Version
6.0.2

### Browser and OS info
Chrome Version 98.0.4758.80 (Official Build) (x86_64) / macOS Catalina 10.15.7

### Steps to reproduce
Create any app and change the state via a mutation

### What is expected?
The state in the Vue Devtools to be updated or that when I press the "refresh" button it updates to the last state

### What is actually happening?
Nothing is getting updated

---
I had to create a getter to get the last version of the state. I think it could be related to what other have reported here: https://github.com/vuejs/vuex/issues/2046

**Comment by EirikSl** [comment]
Same situation, only getters allow to see state changes.

**Comment by art-kc** [comment]
This happened after latest update today.

**Comment by EirikSl** [comment]
Move to Firefox. Here you can install 6.0.6 version and it works well.

**Comment by Akryum** [comment]
Already closed in https://github.com/vuejs/devtools/commit/985d0c85602db30ffbd7fef152f8eb3b3fce0861 (released in 6.0.6).
