### ISSUE TITLE
Vue Devtools: Vuex data doesn't updating

### ISSUE THREAD

**Issue by Mukhammad-Umar** [vuejs/devtools#1717]
### Version
6.0.6

### Browser and OS info
Google Chrome Version 98.0.4758.82 (Official Build) (64-bit)

### Steps to reproduce
Fix refresh button on the right top side of devtools 

### What is expected?
At least data should be updated

### What is actually happening?
Vuex data isn't changing  and refresh button not working as well. Even if I close developer tools and open it again, it didn't work

---
May be do it auto refresh

**Comment by Akryum** [comment]
Duplicate
