### ISSUE TITLE
Bring back Multiple Parent App View

### ISSUE THREAD

**Issue by sitefinitysteve** [vuejs/devtools#1733]
### What problem does this feature solve?
Our site requires multiple (couple) vue "apps" instead of a single app with multiple components. 

The old dev tools would list each app on the root, and child components under them.  It was a great way to see everything on the page.  This new version seems to list every app as a dropdown which makes it tougher to get an at-a-glance overview of what's going on. It also seems to be just mostly empty vertical space with one parent.

Now I realize my use-case is uncommon, but perhaps at least an OPTION on which view defaults in the pane? It's just a honkin waste of vertical space right now with the one root and couple child components, then adding extra clicks to swap.

### What does the proposed API look like?
* Option in the dropdown for "All Apps", which would then obviously be the previous version view with multiple parents on the tree.
* Option in settings to have the All Apps OR Dropdown view system

**Comment by Akryum** [comment]
I implemented UX improvements in [6.0.11](https://github.com/vuejs/devtools/releases/tag/v6.0.11).

**Comment by sitefinitysteve** [comment]
Beautiful! Thank you so much!
