### ISSUE TITLE
Provide option to remove "Slave init complete/Slave loading data..." logs

### ISSUE THREAD

**Issue by jarrodwhitley** [vuejs/devtools#1736]
### What problem does this feature solve?
This problem was initially brought up in this issue. https://github.com/vuejs/devtools/issues/1151

After much discussion, from users the issue was unceremoniously closed by @Akryum without explanation. These excessive console logs are very annoying to deal with. Especially if you're using Electron and have no way to filter them out as you could in Chrome Dev Tools.

Please hear our desperate pleas and fix this issue.

### What does the proposed API look like?
See here: https://github.com/vuejs/devtools/issues/1151

![Screen Shot 2022-02-14 at 3 33 16 PM](https://user-images.githubusercontent.com/11711674/153950049-f4802d67-1134-4534-8627-e4a11b371d58.png)

**Comment by Akryum** [comment]
Is it possible to stop being rude and open a real bug report? Thank you.
