### ISSUE TITLE
Cannot manually update vuex state in vuex tab

### ISSUE THREAD

**Issue by art-kc** [vuejs/devtools#1737]
### Version
6.0.8

### Browser and OS info
Mac OS Chrome lates

### Steps to reproduce
Open chrome dev tools
Choose vuex tab
Find any state property and try to edit it
Save edits

### What is expected?
state property should update

### What is actually happening?
state property stays as before.

**Comment by Akryum** [comment]
Please provide a runnable reproduction with the libraries you use and provide the real version of the devtools you are using. Thanks.

**Comment by art-kc** [comment]
6.08 Any app with vuex and namespaced state enabled
https://demo.vuestorefront.io/
