### ISSUE TITLE
alt-click to recursively expand component tree

### ISSUE THREAD

**Issue by hafdon** [vuejs/devtools#1739]
### Version
6.0.9

### Browser and OS info
chrome LTS, windows 10

### Steps to reproduce
open vue dev tools, go to Components tab, alt-click on arrow next to component, see that tree does NOT recursively open

### What is expected?
tree to recursively open (was standard on devtools before Vue3 became default)

### What is actually happening?
just opens 1 layer

---
please bring this feature back

**Comment by arm-liang** [comment]
feat: double click or enter key to expand current node
