### ISSUE TITLE
Unable to use multi-node mode

### ISSUE THREAD

**Issue by nigiwen** [vuejs/devtools#174]

**Comment by webfansplz** [comment]
Hi,I can’t understand what’s your meaning. Can you provide a mini repo, thanks!

**Comment by webfansplz** [comment]
> ![image](https://private-user-images.githubusercontent.com/67454874/297113868-4811808a-a205-433e-8f39-869f00c936b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjE5OTAsIm5iZiI6MTcwNTQyMTY5MCwicGF0aCI6Ii82NzQ1NDg3NC8yOTcxMTM4NjgtNDgxMTgwOGEtYTIwNS00MzNlLThmMzktODY5ZjAwYzkzNmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE2MTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MzU1MThhNTRmZmQ3YWJmYmNmOTg0MmEyN2VhMWVhNTA2YTgyMDY3Mjg5MzM2MDdiMjgxYTNhYjVmZmE5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fIj_paPMugJ_qic7--MX5vNa729hR0coS_9i8cnNjSA)
> 
> So that's it

Thank you for the feedback, I’ll add it to the document.
