### ISSUE TITLE
backend.js:704 An error occurred in hook 'getInspectorState' registered by plugin 'org.vuejs.vue2-internal' with payload:

### ISSUE THREAD

**Issue by angelloredo** [vuejs/devtools#1757]
### Version
6.0.12

### Browser and OS info
Chrome 98.0.4758.102 / Windows 10 

### Steps to reproduce
when the vuex panel is opened, Im using vuex with modules and vuex v3.0

### What is expected?
be able to inspect the vuex state

**Comment by didagu** [comment]
I am currently having the issue. Have you solved it yet ?@angelloredo

**Comment by epixian** [comment]
I also get the following console error:
```
TypeError: getters is undefined
    formatStoreForInspectorState moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:5379
    setupPlugin moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:5057
    handler moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:691
    callHandlers moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:712
    callHook moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:197
    getInspectorState moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:411
    sendInspectorState moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:2500
    connectBridge moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:2373
    wrappedListener moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:6778
    emit moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:10220
    _emit moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:6850
    Bridge moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:6763
    Bridge moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:6763
    listener moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:13850
    listen moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:13854
    Bridge moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:6761
    handshake moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:13846
    EventListener.handleEvent* moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:13831
    <anonymous> moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:13880
    <anonymous> moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js:13882
[backend.js:715:19](moz-extension://0cb3ac7d-f3ba-4549-8e5e-46a7a1305559/build/backend.js)
```

**Comment by rafaelmonroy** [comment]
I fixed issue by removing vue dev tools, making sure I was in developer mode in google chrome extensions and added vue dev tools again.

**Comment by yanpaop** [comment]
I'm having the same problem and reinstalling doesn't work

**Comment by lisongtao0704** [comment]
mac上遇到同一个问题，重装没用

**Comment by lisongtao0704** [comment]
mac上遇到这个问题,报错如图。<img width="975" alt="image" src="https://user-images.githubusercontent.com/69238683/160294389-8e4bae2b-9989-4199-aba7-e2151a8f7963.png">
我是使用registerModule动态注册的状态管理模块

**Comment by xnextx** [comment]
I have the same problem :(

**Comment by shandrolis** [comment]
I see that this issue is closed because https://github.com/vuejs/devtools/commit/107589b3517956b1c8afaad2beedc714443d6c17 was supposed to fix this, but I am still experiencing this issue on version 6.1.4.
Anyone else?

**Comment by firstnoodle** [comment]
I'm also still having this issue.

**Comment by alexventuraio** [comment]
Started to have the issue today version 6.1.4 Mac OS Big Sur ARM - Brave browser

**Comment by YuanWenLai** [comment]
I have the same problem，too

**Comment by PKTseng** [comment]
I'm add modules files in store, and in modules file add user.js, then problem is fixed.

vue version: 2.6.11
vuex version: 3.4.0

**Comment by VishalBhandare-Apertumo** [comment]
In my case i face this error while i was using wrong naming convention for getter
```
'moduleName/child': (state) => state.userdetailother,

  // single type user detail
  'moduleName/child/single/data': (state) => state.userdetail.data,
  'moduleName/child/single/loading': (state) =>
    state.userdetail.loading,
  'moduleName/child/single/offset': (state) =>
    state.userdetail.offset,
```
Seems below is wrong and should be avoid.
'moduleName/child'
 'moduleName/child/single/data'
 May be issue comes when there is some wrong names used for getter.

 Hope this help to someone.

**Comment by Master-Y0da** [comment]
Having this same problem with pinia...Any help ?

**Comment by rizalrenaldi** [comment]
Uninstall Vue dev extension and reinstalling it again solved the error, as stated by @rafaelmonroy

**Comment by apfrod** [comment]
I had this issue and found it was due to a naming collision. I had a root getter with the same name as a module.

**Comment by diegopousas** [comment]
Tive o mesmo problema em 22/11/2023.
Desinstalei o Vue DevTools e resolveu. ;)
