### ISSUE TITLE
I'm unable to change state through the vuex plugin like I used to. Bring this feature back PLEASE

### ISSUE THREAD

**Issue by shresgav** [vuejs/devtools#1769]
### What problem does this feature solve?
In the previous major version of vue devtools I used to be able to change feature flags on my web app to true or false very easily through the vue devtools, but now I can't. This was a really quick and unobtrusive way to validate that my feature flags were working as intended

### What does the proposed API look like?
I would like the vuex plugin to look like it used to. Vue devtools was so much better before.

**Comment by Akryum** [comment]
If you have problems with Vuex editing, please open a real issue with more info and a reproduction (and preferably without your unrespectful tone). Thank you.
