### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by kotlyarchuks** [vuejs/devtools#1770]
### Version
6.0.12

### Browser and OS info
Chrome 98.0.4758.102 / Windows 10

### Steps to reproduce
page with Vue 3 app, opening or refreshing prints errors in console for every child component in tree

backend.js:704 An error occurred in hook 'walkComponentParents' with payload

TypeError: Cannot read properties of null (reading 'instanceMap')
    at ComponentWalker.mark (backend.js:6148:51)
    at ComponentWalker.captureId (backend.js:6051:10)
    at ComponentWalker.getComponentParents (backend.js:5945:10)
    at backend.js:6333:40
    at DevtoolsHookable.callHandlers (backend.js:702:17)
    at DevtoolsApi.callHook (backend.js:192:29)
    at DevtoolsApi.walkComponentParents (backend.js:270:32)
    at Object.<anonymous> (backend.js:1941:61)

### What is expected?
no errors

### What is actually happening?
errors

**Comment by Akryum** [comment]
Please provide a runnable reproduction, thanks.

**Comment by sebaguse** [comment]
I have the same issue, not really sure what is the root cause

**Comment by nicecue** [comment]
2backend.js:2190 Uncaught TypeError: Cannot read properties of null (reading 'instanceMap')
    at Bridge.<anonymous> (backend.js:2190:55)
    at Bridge.emit (backend.js:8443:5)
    at Bridge._emit (backend.js:6446:12)
    at backend.js:6372:42
    at Array.forEach (<anonymous>)
    at backend.js:6372:18
    at listener (backend.js:11997:13)
(anonymous) @ backend.js:2190
emit @ backend.js:8443
_emit @ backend.js:6446
(anonymous) @ backend.js:6372
(anonymous) @ backend.js:6372
listener @ backend.js:11997
postMessage (async)
n @ proxy.js:1
backend.js:3326 Timeline layer mouse not found

**Comment by hansonfang** [comment]
same problem

**Comment by tks-007** [comment]
![image](https://user-images.githubusercontent.com/29967295/157826323-9ba4e2f5-b90d-4940-9878-8a411c52e656.png)
打开控制台还能vuedevtools就报错

**Comment by Akryum** [comment]
@tks-007 please update Vue, looks like you are on an older version.

**Comment by hansonfang** [comment]
> 

Is this related to Vue version? I had to use Vue2 and Vue3 in a single page since I've used micro frontend

**Comment by symmetriq** [comment]
I have the same issue. We currently have a mix of Vue 2 (2.6.14) and Vue 3 (3.2.31) components.

The beta version of Vue Dev Tools (6.0.0 beta 21) does not have this issue, so I have reverted back to the beta again.

**Comment by gewisser** [comment]
Vue Dev Tools 6.1.4

![image](https://user-images.githubusercontent.com/5417292/167273418-0ee7ad6f-661f-4520-9973-09f514b83d73.png)


![image](https://user-images.githubusercontent.com/5417292/167273398-799d5064-46d6-42e5-9b1e-03faca5ddf55.png)

**Comment by gewisser** [comment]
Repo: https://github.com/gewisser/VueToolsBug

```bash
npm install
npm run dev
```

1. open http://localhost:9000/
2. open DevTools (F12)
3. activate the tab "Vue"
4. reload page (F5)

**Comment by HC200ok** [comment]
What about reinstall your vuejs devtools?
https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

**Comment by gewisser** [comment]
> What about reinstall your vuejs devtools? https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

Thanks! Reinstalled vuejs devtools. In my case the problem is gone.

**Comment by mobsean** [comment]
> > What about reinstall your vuejs devtools? https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd
> 
> Thanks! Reinstalled vuejs devtools. In my case the problem is gone.

this works. Issue should be closed, I think

**Comment by kspackman** [comment]
Seeing the same issue on Vue DevTools 6.1.4. Vue 3.2.31 and 3.2.37. Hundreds of repeated console errors. Any updates on it, @Akryum?

**Comment by symmetriq** [comment]
Still not working here. Exact same issue as before (`An error occurred in hook 'walkComponentParents' with payload`, repeated over and over in the console). Reinstalling doesn't solve the problem. As I mentioned before, we're using both Vue 2 (2.6.11) and Vue 3 (3.2.30).

The beta version (6.0.0 beta 21) still works fine, but after upgrading vue-router to the latest version (4.1.3), it's now complaining that I'm still on the Dev Tools beta and router links don't work when Dev Tools is open. So this issue is now preventing vue-router upgrades.

**Comment by cantkillemall** [comment]
I confirm I have this message ONLY when the Vue Devtools 6.2.1 is activated. Console remains silent when deactivated.
Error appeared after upgrading from Nuxt 3 RC6 to RC8.
![with vue devtools](https://user-images.githubusercontent.com/378805/185320827-53b4f333-c508-44b5-a18b-524d98911b07.png)
![without vue devtools](https://user-images.githubusercontent.com/378805/185320860-61b5834f-847d-4201-b580-e4cafef30ce2.png)
.

**Comment by nurRiyad** [comment]
I had the same issue in nuxt-rc8. Reinstalling the Vue dev tool solved my issue

**Comment by paolodina** [comment]
FWIW, I see the same issue with Vue 3.2.41, but only when Chrome DevTools Network throttling set to 3G, with no error on regular network settings.

**Comment by dpmango** [comment]
> What about reinstall your vuejs devtools? https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

It actually works. Had issue with Nuxt 3.1.x throwing `hook 'walkComponentParents' `

**Comment by Fil923** [comment]
I've tried multiple time reinstalling the extension but i'm still having errors in console trying to modify the value of a ref inside custom components.
Vue 2.7.14/ devtools 6.50

**Comment by seb-guz** [comment]
same problem for me, reinstalled devtools and the problem still exists

**Comment by GLaDOS-Mesa** [comment]
Same issue here!
Vue v. 2.7.14 with Composition API
DevTool v. 6.5.0

**Comment by wuduo0701** [comment]
I had the same problem, repeated reinstall didn't work.
Vue v. 2.7.14 DevTool v. 6.5.0

**Comment by wuduo0701** [comment]
I had the same problem, repeated reinstall the extension didn't work.
Vue v. 2.6.11 / DevTool v. 6.5.0

**Comment by rebz** [comment]
This has been on ongoing issue for the better part of a year, attempting to debug this in a large app has been painful.

```
vue: 3.2.47
devtools: 6.5.0
```

**Comment by conorhooley** [comment]
Also experiencing this on an app being migrated to Vue 3. `Vue 3.2.47` & `devtools 6.5.0`. Clearing & reinstalling `node_modules` didn't work, nor did removing & reinstalling the Chrome extension.

**Comment by davide-granello** [comment]
same issue

**Comment by rebz** [comment]
> This has been an ongoing issue for the better part of a year, attempting to debug this in a large app has been painful.
> 
> ```
> vue: 3.2.47
> devtools: 6.5.0
> ```
> 
> No amount of uninstalling (devtools), re-installing, clearing node_modules, clearing yarn cache, deleting the `yarn.lock` file, etc... fixes this.
> 
> I've updated our app to only load 2 components, the Root Component, and an empty component (just a paragraph tag inside). The error will occur and reference the empty component VNode.
> 
> I've tried creating a sandbox of this to share, but I can't seem to replicate it.
> 
> Still digging.

Coming back to state that the error no longer occurs. We are currently on `"vue": "^3.3.2",`, we were seeing this on `3.2.47`. I have no reason to believe that upgrading Vue solved it.

I don't know when the error stopped exactly, and looking through our commits/MRs I cannot see anything specifically that would have been a potential trigger. Worth noting that we are still migrating to Vue 3 and a lot more components have been updated.

I know this doesn't help anyone still experiencing the issue. I have no reason to believe that upgrading Vue solved it. I do believe it is something relevant to our codebase, but unfortunately do not know what.

If I see something that stands out as we continue moving forward I'll come back and post in this thread. For now I am under the belief this is not an issue with this repo.

**Comment by vedmant** [comment]
I have the same problem, in my case its Nuxt 3 app and this errors start to appear when I set `ssr: false,` in the Nuxt config. Also this breaks hot reloading.

**Comment by lukas-vollmer** [comment]
Had same problem with nuxt version 3.7.3. Worked after I allowed "Allow access to file URLs":
https://github.com/vuejs/devtools/issues/1760#issuecomment-1221319674

**Comment by TimvdEijnden** [comment]
@lukas-vollmer Thanks, this also resolved the issue for me. 

I was afraid the error was caused by my application, costed a lot of time to figure out it was caused by de the Vue Dev tools

**Comment by TimGuendel** [comment]
Same Problem with Nuxt 3.7.4
Lukas' Solution fixed it too.
