### ISSUE TITLE
Can't modify state value of pinia store if state value is null

### ISSUE THREAD

**Issue by enrikqose** [vuejs/devtools#1776]
### Version
6.0.12

### Browser and OS info
Chrome 98 / Windows 10

### Steps to reproduce
Try to modify the value of a state of a pinia store that has a value of null

### What is expected?
The state should get the new value

### What is actually happening?
backend.js:704 An error occurred in hook 'editInspectorState' registered by plugin 'dev.esm.pinia' with payload: {inspectorId: 'pinia', app: {…}, nodeId: 'auth', path: Array(1), type: 'state', …}
callHandlers @ backend.js:704
callHook @ backend.js:195
await in callHook (async)
editInspectorState @ backend.js:422
editInspectorState @ backend.js:2451
(anonymous) @ backend.js:2329
await in (anonymous) (async)
wrappedListener @ backend.js:6568
emit @ backend.js:10007
_emit @ backend.js:6640
(anonymous) @ backend.js:6553
(anonymous) @ backend.js:6553
listener @ backend.js:13561
postMessage (async)
n @ proxy.js:1

backend.js:705 TypeError: Cannot read properties of null (reading '__v_isRef')
    at StateEditor.api.stateEditor.isRef (backend.js:6375:46)
    at backend.js:6903:18
    at StateEditor.set (backend.js:6845:7)
    at Object.set (backend.js:431:84)
    at pinia.esm-browser.js:641:25
    at handler (backend.js:681:16)
    at DevtoolsHookable.callHandlers (backend.js:702:17)
    at DevtoolsApi.callHook (backend.js:195:26)
    at async DevtoolsApi.editInspectorState (backend.js:422:5)
    at async editInspectorState (backend.js:2451:3)
callHandlers @ backend.js:705
callHook @ backend.js:195
await in callHook (async)
editInspectorState @ backend.js:422
editInspectorState @ backend.js:2451
(anonymous) @ backend.js:2329
await in (anonymous) (async)
wrappedListener @ backend.js:6568
emit @ backend.js:10007
_emit @ backend.js:6640
(anonymous) @ backend.js:6553
(anonymous) @ backend.js:6553
listener @ backend.js:13561
postMessage (async)
n @ proxy.js:1

**Comment by Akryum** [comment]
Maybe open an issue in the pinia repo first.
