### ISSUE TITLE
this version is horrible

### ISSUE THREAD

**Issue by PiotrSzczeszek** [vuejs/devtools#1778]
### Version
6.0.12

### Browser and OS info
edge 98 / windws 10

### Steps to reproduce
Just using the dev tools

### What is expected?
Clear UI,
quick loading time,
double click on tree view list
the timeline is just horrible

### What is actually happening?
Soo... previous version was so much superior to this one. Firs of all the double click on the vue components (the components tree view) used to expand the child elements. It does not do it anymore. I don't want to select / copy the name of this component - I want to get to the inner element only.

Second thing is this horrible timeline. Events do not scroll automatically, as the new one appear, but stay in place. But the most frustrating thing is that even a quick hover over the elements causes my page to load state at the time the event happened.
This feature is neat - I'd love to use it SOMETIMES, but not when i just want just a little bit of information about the events that happened.

And what happened to menu section? It used to be really clear - separate tabs for vues / events etc. Now everyfing is squished together. The timeline view is cool - it's nice to know what happened in what order, but I would love to see the separate tabs for each element again.

And the last thing - compared to previous version it's just laggy :/

**Comment by d-ryabtsev** [comment]
> If you intend to give constructive feedback, maybe consider not starting it with a insulting headline.
> 
> It makes you look like a horrible person.

Sorry but this answer is not good enough. The new version of Vue dev tools is horrible. You should give people the option to switch back to the old.

**Comment by yyx990803** [comment]
@d-ryabtsev 

1. The option has always been there: https://chrome.google.com/webstore/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp

2. In case you don't understand like OP, insulting maintainers will get you nowhere. OSS maintainers are people with emotions, and guess what - they don't owe you shit (surprise!). If you don't or can't communicate respectfully, whatever your opinion is, it will just be ignored. Simple as that.
