### ISSUE TITLE
Revert the UI of vue devtools

### ISSUE THREAD

**Issue by besmiralia** [vuejs/devtools#1781]
### What problem does this feature solve?
The new UI is so unintuitive to use. I can't find the components I'm looking for, everything shows App 1,  App2, etc. On top of that, none of those are the component rendered in the screen which I'm looking for.
I don't even know how to navigate this. The old UI was so much easier to work with

### What does the proposed API look like?
I know you will disregard this, because every developer has an ego that is hard to deal with.

**Comment by Akryum** [comment]
This is issue is so unconstructive and passive-aggressive that yeah, I'm gonna close it. Please open [a discussion](https://github.com/vuejs/devtools/discussions) with constructive ideas and feedback instead of polluting the issues.
