### ISSUE TITLE
Extension is temporary unavailable on the Chrome web store

### ISSUE THREAD

**Issue by Akryum** [vuejs/devtools#1795]
![image](https://user-images.githubusercontent.com/2798204/158230769-807b0fc4-2b33-4504-9e41-3ee40ebcf0fc.png)

It is being restored as soon as possible. Meanwhile, please follow this guide to install the extension on Chrome:

- Download the `devtools-chrome` zip I've put here: https://github.com/vuejs/devtools/releases/tag/v6.1.3
- Extract it
- Open the Chrome extensions tab
- Enable  "Developer mode"
- Click on "Load unpacked"
- Select the extracted folder

Alternatively, you can install it [on Firefox](https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/).

**Comment by kiccer** [comment]
I also found this just now, I installed version `6.0.13`, but I searched the store for `vue-devtools` tools, but I see version `6.0.0.21`, is this a version rollback happening?

**Comment by Akryum** [comment]
The extension page is [back](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)
