### ISSUE TITLE
Uncaught ReferenceError: r is not defined

### ISSUE THREAD

**Issue by Chen-913** [vuejs/devtools#1797]
### Version
6.1.1

### Browser and OS info
Chrome 99 /Windows 10

### Steps to reproduce
1. 前往Chrome Web Store
2. 移除旧版的Vue.js devtools 6.1.0
3. 安装最新版Vue.js devtools 6.1.1

### What is expected?
在控制台中有Vue的选项，并且不报错

### What is actually happening?
控制台报错，并且没有Vue选项卡
报错信息如下：
VM20:1 
        
       Uncaught ReferenceError: r is not defined
    at l (<anonymous>:1:439)
    at o (<anonymous>:1:560)
    at <anonymous>:1:6029

![image](https://user-images.githubusercontent.com/72293244/158353412-d10615d0-d07e-4069-94ba-e66391970b4a.png)

**Comment by Akryum** [comment]
This has already been fixed in [6.1.2](https://github.com/vuejs/devtools/releases/tag/v6.1.2) (`hook import not working`).
