### ISSUE TITLE
pinia menu not show when i use devtools  as standalone application (work in Electron)

### ISSUE THREAD

**Issue by PARADISELIN** [vuejs/devtools#1799]
### Version
6.1.3

### Browser and OS info
MacOS 12.1

### Steps to reproduce
step 1:

```shell
pnpm install @vue/devtools -D
```

step2: connect
```ts
import { createApp } from 'vue'
import { createPinia } from 'pinia'

import App from './App'

if (__DEV__) {
  require('@vue/devtools').connect('http://localhost', 8098)
}

export default function () {
  const app = createApp(App)
  app.use(createPinia())
  return app
}
```

### What is expected?
Expecting it will have a pinia menu for debugging like in chrome's extension

### What is actually happening?
It works fine, but it's missing the pinia menu

**Comment by xgqfrms** [comment]
what's the solution?

**Comment by bernardoadc** [comment]
@PARADISELIN have you found the solution?

**Comment by softboy99** [comment]
problem still exists in 6.5.1
