### ISSUE TITLE
New Version is bad for UI/UX then before version

### ISSUE THREAD

**Issue by kydner** [vuejs/devtools#1800]
### Version
6.1.3

### Browser and OS info
firefox, chrome

### What is actually happening?
 

---

**Comment by swastupuri** [comment]
![FMbbTMQaQAABEKv](https://user-images.githubusercontent.com/4133837/158783796-952e5207-b078-4b55-a361-c378a6319025.jpeg)
the new devtool look so confusing, I have 8 vue apps with version 2.. I can't tell which one I need to inspect unless I visit them 1 by 1..  The previous version is much easier..

also the component custom event inspector not immediately shown without visiting timeline -> Component Events.. the navigation is too nested

**Comment by Akryum** [comment]
Please use discussion: https://github.com/vuejs/devtools/discussions/1793
