### ISSUE TITLE
bug: Pinia panel not exist on vue devtools

### ISSUE THREAD

**Issue by xgqfrms** [vuejs/devtools#1839]
### Version
6.1.4

### Browser and OS info
 Chrome 100.0.4896.88 / macOS 12.3

### Steps to reproduce

```sh
# 1. create project
$ npm create vite@latest vue3-ts-pinia -- --template vue-ts

#  install pinia
$ npm i -S pinia
```

```js
// 2. use pinia

import { createApp } from 'vue';
import App from './App.vue';

import { createPinia } from 'pinia';

const app = createApp(App);

// const pinia = createPinia();
// app.use(pinia);

app.use(createPinia());

createApp(App).mount('#app');


```

```js
// 3. create store
import { defineStore } from 'pinia';

export const appStore = defineStore('appStore', {
  state() {
    return {
      msg: "Hello World!",
    };
  },
  getters: {
    // computed
    getMsg(): string {
      return `👻 ${this.msg}`;
    }
  },
  actions: {
    // methods
    updateMsg(str: string) {
      this.msg = str;
    },
    async fetchData(url: string) {
      const json = await fetch(url).then(res => res.json());
      // console.log('json =', json);
      return json;
    },
  },
});

```

```vue
<!-- 4. use store -->
<template>
  <template v-if="true">
    <div>{{store.msg}}</div>
  </template>
  <template v-if="true">
    <div>{{store.getMsg}}</div>
    <pre>❓ {{store.msg}}</pre>
    <span v-pre>{{ this will not be compiled }}❓ {{store.msg}}</span>
    <button @click="updateMsg">Pinia 🍍</button>
  </template>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { appStore } from "../store/index";
const store = appStore();
const log = console.log;
log(`store =`, store);

const updateMsg = () => {
  store.$patch({
    msg: "Hello Pinia 🍍!",
  });
  // store.updateMsg('Pinia 🍍');
}

let jsonString = ref('');
const url = `https://cdn.xgqfrms.xyz/json/cat.json`;
// async await
store.fetchData(url).then(json => {
  jsonString.value = JSON.stringify(json, null, 4);
});

</script>

```

```json
{
  "name": "vue3-ts-pinia",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "pinia": "^2.0.13",
    "vue": "^3.2.25"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.3.1",
    "typescript": "^4.5.4",
    "vite": "^2.9.2",
    "vue-tsc": "^0.29.8"
  }
}
```

5.  run `npm run dev` and open `http://localhost:3000/`

### What is expected?
Pinia panel exists on vue devtools and works well ✅

![image](https://user-images.githubusercontent.com/7291672/164228227-3edc9796-adaf-4d60-b3ad-c4b6622011da.png)

### What is actually happening?
Pinia panel does not exist on vue devtools ❌

![image](https://user-images.githubusercontent.com/7291672/164228074-ef040663-363a-4b82-9370-3f6f16111d79.png)

---

**Comment by Akryum** [comment]
Did you do the pinia setup in your app?
```js
import { createPinia } from 'pinia'

app.use(createPinia())
```

**Comment by xgqfrms** [comment]
@Akryum yeah, I did that.

![image](https://user-images.githubusercontent.com/7291672/167301214-0c7b8ec3-86e9-456d-8f84-8221a2aafe75.png)

**Comment by xgqfrms** [comment]
# solutions ✅


```diff
// 2. use pinia
import { createApp } from 'vue';
import App from './App.vue';
import { createPinia } from 'pinia';

const app = createApp(App);

app.use(createPinia());

- createApp(App).mount('#app');
+ app.mount('#app');

```


```diff
// 2. use pinia
import { createApp } from 'vue';
import App from './App.vue';
import { createPinia } from 'pinia';

- const app = createApp(App);
- app.use(createPinia());
- createApp(App).mount('#app');

+ createApp(App).use(createPinia()).mount('#app');

```

**Comment by bernardoadc** [comment]
any idea how to do this in vue2?

**Comment by mptap** [comment]
A solution that worked for me was to force it with another Chrome extension: https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

**Comment by ZubyApp** [comment]
what worked for me was

app.use(createPinia()) and then making it the last  just before app.mount('#app')

**Comment by justincpollard** [comment]
@bernardoadc moving the pinia instance towards the end of Vue's constructor args did the trick for me, though not sure why:
```
new Vue({
    router,
    i18n,
    pinia,
    render: (h) => h(App),
}).$mount('#app')
```

**Comment by SD-Gaming** [comment]
> @bernardoadc moving the pinia instance towards the end of Vue's constructor args did the trick for me, though not sure why:
> 
> ```
> new Vue({
>     router,
>     i18n,
>     pinia,
>     render: (h) => h(App),
> }).$mount('#app')
> ```

I just wanted to let you know that it works for me.

**Comment by Marcuse7** [comment]
Using _quasar_, the following worked for me:

```
import { boot } from 'quasar/wrappers'
import { createPinia, setActivePinia } from 'pinia'

export default boot(({ app }) => {
    const pinia = createPinia()
    setActivePinia(pinia)

    app.use(pinia).mount('q-app')
})
```

**Comment by suterma** [comment]
> + createApp(App).use(createPinia()).mount('#app');

It really seems to be that `createPinia()` must be called in a chained fashion. It did not work for me when I did like the OP initially, but now with the chained approach, this works flawlessly. 

One wonders what the underlying cause is...

**Comment by softboy99** [comment]
Hi,
 @suterma, i changed to chained fashion, still not work, Why?

`async function bootstrap() {
  // 创建应用实例
  const app = createApp(App);

  // 多语言配置,异步情况:语言文件可以从服务器端获得
  await setupI18n(app);

  // 配置存储
  setupStore(app);

  // 初始化内部系统配置
  initAppConfigStore();

  // 注册外部模块路由(注册online模块lib)
  registerPackages(app);

  // 注册全局组件
  registerGlobComp(app);

  //CAS单点登录
  await useSso().ssoLogin();

  // 配置路由
  setupRouter(app);

  // 路由保护
  setupRouterGuard(router);

  // 注册全局指令
  setupGlobDirectives(app);

  // 配置全局错误处理
  setupErrorHandle(app);

  // 注册第三方组件
  await registerThirdComp(app);

  // 当路由准备好时再执行挂载( https://next.router.vuejs.org/api/#isready)
  await router.isReady();

  // 挂载应用
  app.mount('#app', true);

  console.log(' vue3 app 加载完成！');
}

bootstrap();
`

**Comment by simply-none** [comment]
> > * createApp(App).use(createPinia()).mount('#app');
> 
> It really seems to be that `createPinia()` must be called in a chained fashion. It did not work for me when I did like @xgqfrms initially, but now with the chained approach, this works flawlessly.
> 
> One wonders what the underlying cause is...

no, the `app.use(createPinia())` must in the end of all `app.use` and before the `app.mount`

**Comment by PrestaSafe** [comment]
Same issue here
fixed by using: 
```
import './index.css'
const app = createApp(App).use(createPinia())
app.mount('#app')
```

instead of: 
```
const pinia = createPinia()
import './index.css'
const app = createApp(App).use(pinia)
app.mount('#app')

```
🤷‍♂️ 
Thanks for the tips anyway :)
