### ISSUE TITLE
Chrome shortcuts triggered when input tag is focused

### ISSUE THREAD

**Issue by konpeki622** [vuejs/devtools#1846]
### Version
6.1.4

### Browser and OS info
Chrome 96 / Windows 10

### Steps to reproduce
This issue was feedbacked from #1598 @dkjain : 
> These new shortcuts Alt + F and Alt + D overlaps with Chrome's shortcuts mean, if Filter State input box is focused (Alt + D) and getting focus Filter component input (Alt + F), chromes three vertical dot menu (towards top-right) button/trigger steals focus. And same when filter component input is focused (Alt + F) and now trying to focus filter state input (Alt + D), chrome's omnibar gets focused.

I have verified this situation and it actually exists.

### What is expected?
We can use Alt + F and Alt + D on devtools well.

### What is actually happening?
Chrome shortcuts triggered.

**Comment by Akryum** [comment]
The issue is that my keyboard logic is disabled when you are in an input field (for example to allow you to use keyboard arrows). It should be enforced for certain cases (such as shortcuts with Alt).
