### ISSUE TITLE
Make the selected component available as $0 in the console (as in old vue devtools version)

### ISSUE THREAD

**Issue by jbruni** [vuejs/devtools#1851]
### What problem does this feature solve?
It is extremely handy and useful to be able to access the component's "vm" object instance when developing and debugging. Older Vue DevTools provided this feature, which I used a lot - and now I am missing it a lot.

### What does the proposed API look like?
Just bring back that functionality, please. When clicking at a component in the component's hierarchy tree shown at Vue DevTools, that component's "vm" should be made available as $0 in the console. Just like when we click at an element at the Elements inspector, and the corresponding DOM element is made available as $0 in the console. Please.

**Comment by Akryum** [comment]
`$0` is a variable created by the browser when you select an element in the dom inspector.
Like it always did, you can access the selected Vue component from vue-devtools with `$vm` (or `$vm0`, `$vm1`, etc.).
