### ISSUE TITLE
"Serialize and copy the state" does not appear to copy to clipboard

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/devtools#1856]
### Version
6.1.4

### Browser and OS info
Edge 101 / Windows 11

### Steps to reproduce
With the Pinia tab active, I clicked on "Serialize and copy the state". In another app, I pasted, and nothing was in the clipboard.

### What is expected?
I expected a JSON version of the state. 

### What is actually happening?
Nothing is saved to the clipboard.

**Comment by Akryum** [comment]
Please open an issue on the pinia repository. Pinia's devtools plugin is not maintained here.
