### ISSUE TITLE
vue-devtools standalone not displaying components, vuex, etc. - no app in the selector

### ISSUE THREAD

**Issue by Darkyn** [vuejs/devtools#1864]
### Version
6.1.4

### Browser and OS info
Version 101.0.4951.67 (Official Build) (64-bit) / Windows 10

### Steps to reproduce
1. Load vue-devtools standalone
2. Refresh the vue app with "local:8089" js included 
2. devtools seems to detect the app but no app available in the selector and no components are shown in the UI

### What is expected?
Should see the component tree in the UI.

### What is actually happening?
Components aren't loading at all and it looks like no app is available in the selector.

**Comment by mikgeorges** [comment]
Same happens to me.

**Browser and OS Info:**
Version 101.0.4951.64 (Official Build) (arm64) / MacOS Big Sur

**Comment by Darkyn** [comment]
Quick note...I reverted back to 5.3.4 with the same result.

**Comment by Prooksius** [comment]
The same, helps only if I restart browser

**Comment by Darkyn** [comment]
Anyone have any info on this for the standalone version? Used to work great but for some reason, nothing shows in the UI anymore, and it just says "No app". Downgrading to a lower version doesn't help either.

**Comment by Darkyn** [comment]
Another quick note...when I view console within the standalone devtools Electron app, I see this in the console:

Uncaught TypeError: Cannot read property 'view' of null

and

NavigationDuplicated: Avoided redundant navigation to current location: "/"

This is within the standalone devtools app itself though.

**Comment by Darkyn** [comment]
Ok, so I'm feeling a little silly at the moment...

After spending an entire day on this, I realized that I was using a prod build instead of a dev build which was why there wasn't any info for dev-tools to display. DOH! Closing this with shame lol ;)

**Comment by TiagoSilvaPereira** [comment]
@Darkyn what did you make to fix this problem?

**Comment by Darkyn** [comment]
Hey @TiagoSilvaPereira in my case, I just needed to rerun **npm** with **watch** (`npm run dev` or `npm run watch`). The problem was just that I had been running with a prod build so there was no symbol info for devtools. At least that's my assumption. I can reproduce it by building with prod, checking devtools (no info) and then rebuilding with dev (lots of info).
