### ISSUE TITLE
Select component in the page hotkey changed

### ISSUE THREAD

**Issue by avxkim** [vuejs/devtools#1907]
### Version
6.2.0

### Browser and OS info
Chrome Version 103.0.5060.114 (Official Build) (arm64) / MacOS 12.4

### Steps to reproduce
1. Open devtools
2. Press  ⌥ + S

### What is expected?
I can select any component on the page

### What is actually happening?
Nothing changes after i press ⌥ + S

**Comment by acmu** [comment]
I have the same situation , why the hot key ⌥ + S is not useful ?
the previous version , hot key `s` is ok.

**Comment by theo-bittencourt** [comment]
Same here.

* MacOS 12.5
* Chrome Version 103.0.5060.134 (Official Build) (x86_64)
* Vue Dev Tools 6.2.1

**Comment by acmu** [comment]
can you help we for this?  @Akryum

**Comment by HBunnick** [comment]
Same here
Reproduceable for me on:
latest Firefox, latest Waterfox, latest Chrome, on Mac OS: 12.6, 12.5

**Comment by djpowers** [comment]
I've been seeing the same for a while now. I believe the previous keyboard shortcut of just "s" functioned properly for me, but currently no combination works.

With the Vue DevTools panel active, trying both `⌥ + s`  and `⌥ + ⇧ + s` (in case it's expecting a capital "S") do not bring up the select component tool.

- macOS 12.6.2
- Firefox 109.0b2
- Vue.js devtools 6.4.5

**Comment by theo-bittencourt** [comment]
Still not working.
