### ISSUE TITLE
Vue devtools cannot view setup data from Vue 2.7

### ISSUE THREAD

**Issue by jostrander** [vuejs/devtools#1908]
### Version
6.2.0

### Browser and OS info
Firefox 102 / Linux

### Steps to reproduce
Spin up vue 2.7 project, use defineComponent() and return any state in setup() of a component. Devtools will not display any setup data when inspecting components.

Edit: This appears to only break when using `defineComponent` syntax, `script setup` works as intended.

### What is expected?
Vue devtools shows setup state in 2.7 as it does in Vue 3+

### What is actually happening?
The setup area of devtools is missing.

---
It appears related to `_setupProxy` not being available on the component instance.

**Comment by yyx990803** [comment]
fixed via e38c3472
