### ISSUE TITLE
VueDevTools shows "Anonymous Component" for components pre-built

### ISSUE THREAD

**Issue by ruben-keolis** [vuejs/devtools#1911]
### Version
6.2.1

### Browser and OS info
Chrome 103 / Windows 10

### Steps to reproduce
- build sub-components in the ui folder
- npm run dev main app in the front folder
- open a browser and check the Vue DevTools in the Inspectorsection

### What is expected?
Shows sub-components name

### What is actually happening?
Shows "Anonymous Component"
![image](https://user-images.githubusercontent.com/86823129/179489268-f7558c91-91c3-42f1-aab2-5ddaf442fe4e.png)

---
I am working wth Vue 3 (Composition API) on a monorepo project where I have various workspaces and my front is running on dev mode while my ui (imported dependence) needs to be pre-built inorder to dev the front part so basically I build the ui then I run the front in dev mode. So the components in the front folder are properly named in the devToos and I can follow up with the trees but the components loaded from the pre-built ui (in the ui folder) are all named "Anonymmous Component"

**Comment by Akryum** [comment]
Put a `name` option on them. Since they are prebuilt, the `__file` path isn't included on each component definition so the devtools can't guess their name.

**Comment by ruben-keolis** [comment]
> Put a `name` option on them. Since they are prebuilt, the `__file` path isn't included on each component definition so the devtools can't guess their name.

Actually I am working with Composition api so no way to add a name to the component inside the script, I tried adding a name in the template but it didn't change anything.

**Comment by ruben-keolis** [comment]
Not wahat we would consider clean but it works. Hope in the next versions we'll get a proper way to fix that.
Thanks !

**Comment by ruben-keolis** [comment]
Alright ! Thanks again @Akryum !
