### ISSUE TITLE
Pinia devtools timeline events

### ISSUE THREAD

**Issue by Abeldlp** [vuejs/devtools#1923]
### What problem does this feature solve?
It would be nice if you could see the actions called from pinia in the devtools timeline for debugging purposes.
Right now with the pinia plugin in the vue-devtools you can access the stores, and check data on it's live state, but sometimes when I call actions I would love to be able to see what data is being used in those actions.

### What does the proposed API look like?
Implement an action viewer like the one for vuex

**Comment by Akryum** [comment]
Please open an issue in the pinia repository. This repo doesn't contain code to integrate pinia with the devtools. Thanks!
