### ISSUE TITLE
Don't shows component events vith Vue 2.7.8 and script setup

### ISSUE THREAD

**Issue by alex-lit** [vuejs/devtools#1930]
### Version

6.2.1

### Browser and OS info

Chrome 104, Linux Deepin 20.6

### Steps to reproduce

```vue
<template>
  <button @click="emit('fire')">CLick me</button>
</template>

<script setup>
  import { defineEmits } from 'vue';

  const emit = defineEmits(['fire']);
</script>
```

### What is expected?

Dev tools shows component event 'fire'.

### What is actually happening?

Dev tools shows mouse events only.

**Comment by designgears** [comment]
It's fixed already, they haven't done a release yet.
