### ISSUE TITLE
DevTools crash after a while in FireFox 106

### ISSUE THREAD

**Issue by gitpaladin** [vuejs/devtools#1950]
### Version
6.3.0

### Browser and OS info
FireFox Developer Edition 106.0b04 / Windows 10

### Steps to reproduce
1. Open a large project. In my case almost 500+ vue component was loaded.
2. Use DevTools in FireFox 106b.
3. Interact with the dev tools about 5 minutes
4. The dev tools crashed.
5. Close Firefox devtools and reopen the vue devtools can restart normally.
6. After while the vue devtools crashed again.

### What is expected?
The devtools should not be crashed.

### What is actually happening?
The devtools crash frequently.

---
After I upgrade firefox 106, the bug occurred. In Chrome or Firefox 105, it behaves normally (not crash frequently).

**Comment by gitpaladin** [comment]
Just like this

![图片](https://user-images.githubusercontent.com/8654635/192182859-5cd959d2-d47e-4a4a-954b-9556ddd683c3.png)

**Comment by jakarlse88** [comment]
I'm experiencing the same problem starting today on Windows 10 with Firefox DE 106.0b4. On loading my Vue project, I can work with the dev tools for a relatively short time before I run into the same behaviour described above. Reloading the page will start the cycle over. My project is much smaller, with only two views and ~20 components.

**Comment by Akryum** [comment]
Did you experience this on Chrome or Edge too?

**Comment by Akryum** [comment]
The logo on your screenshot is shown when the devtools frontend disconnects from the injected script (mostly when you reload the page). I've tried leaving mine open on Firefox 104 a fairly complex app and it has not disconnected for almost an hour. Could you provide more details such as:
- system specs
- project packages versions
- a reproduction on which it crashes.
There is a chance this is caused by a bug in Firefox 106.

**Comment by Akryum** [comment]
It seems that it does not happen if the tab is always visible (even if not focused)

**Comment by Akryum** [comment]
Looks like Firefox 106 terminates the background scripts if the tab is in the background.

**Comment by pasamsin** [comment]
I'm using macos firefox developer edition version 106.0b9(64 bit) and I'm having the same problem, it keeps restarting about every 30 second.

**Comment by Lsystems** [comment]
> I'm using macos firefox developer edition version 106.0b9(64 bit) and I'm having the same problem, it keeps restarting about every 30 second.

The same here, and if you have a complexe app with canvas and high frequency reactivity use, it crashes once and you have to close the console, reload your page to reopen the console. 30 seconds later, it crashes again.

Firefox 106.0b9 (64 bits) / Windows 10 up to date.

**Comment by Locheed** [comment]
Came to look if it was a known bug. The same is happening here with the newest Firefox Developer Edition. Really frustrating bug.

**Comment by Akryum** [comment]
Firefox has changed the way they handle extension background pages 👀

**Comment by austriker27** [comment]
I'm also encountering this on Firefox Dev edition. Really unfortunate bug with vue dev tools.

**Comment by alexmccabe** [comment]
It's fun that this issue was closed when it's still happening

**Comment by Jacobtims** [comment]
I have the same problem. Every ~30 seconds it disconnects and reconnects. 
Really annoying, temporarily working on Chrome now. 

Firfox: 107.0 (64-bit)
Windows 10: 10.0.19044 Build 19044

**Comment by kovacsdavid** [comment]
I have the same problem. 

Firefox: 107.0 (64-bit)
OS: Ubuntu 22.04.1 LTS

**Comment by jkruse** [comment]
Same problem here, even if tab is in the foreground.

Firefox 107.0 (64-bit)
Windows 10

**Comment by Aviff** [comment]
@Akryum why you close this issue???
bug is not solved.
FireFox after 104 not able to work.

**Comment by Akryum** [comment]
Discussion continued in #1974

**Comment by samalyxx** [comment]
The same problem started with me today it keeps crashing Firefox 108.0.1

**Comment by taylordragoo** [comment]
This problem still exists, and it's bewildering someone thought it was a good idea to close this issue.

**Comment by gitpaladin** [comment]
> This problem still exists, and it's bewildering someone thought it was a good idea to close this issue.

You can use https://github.com/vuejs/devtools/issues/1974#issuecomment-1362763601 addon temporarily. And waiting for https://github.com/vuejs/devtools/pull/2000#issue-1476480820 MR approved.
