### ISSUE TITLE
Infinite loading when linking two objects to each other

### ISSUE THREAD

**Issue by Floppy012** [vuejs/devtools#1953]
### Version
6.4.1

### Browser and OS info
Brave 1.38.119 / Chromium 101.0.4951.67 / Ubuntu 20.04

### Steps to reproduce
```vue
<script setup>
const objects = [{}, {}];
objects[0].next = objects[1];
objects[1].prev = objects[0];
</script>
```

### What is expected?
Vue DevTools should check for recursion and stop at a certain depth. Another solution would be to analyze as the object tree is opened by the user (i believe that's what happens when I print the objects using console.log)

### What is actually happening?
The component inspector is loading infinitely

---
I'm developing a wizard where steps can be nested in each other. The simplest solution to know what the next step from the current step is, would be to link them together (and vice-versa for the "previous" button).

**Comment by Akryum** [comment]
I'm sorry but I cannot reproduce with the provided information. Please post a runnable reproduction thanks!

**Comment by Floppy012** [comment]
I have to apologize for wasting your time. I cannot reproduce it either. I refactored my code for linking the objects and it seems like that even if i use direct object references, devtools work as intended.
