### ISSUE TITLE
Vue DevTools disconnect

### ISSUE THREAD

**Issue by nyunyu95** [vuejs/devtools#1958]
### Version
6.4.2

### Browser and OS info
Chrome 105.0.5195.127, Windows 11

### Steps to reproduce
1 - Open DevTool
2 - Save a file in IDE (with HMR)
3 - The tool got disconnected
4 - Close the brower console
5 - Re-open it

### What is expected?
DevTool should not disconnect

### What is actually happening?
DevTool is disconnected

**Comment by Akryum** [comment]
Hello, I cannot reproduce with the provided information. Please provide a runnable reproduction, thanks!

**Comment by nyunyu95** [comment]
I don't know how i could "show" you this but i'm on the "Vue Land" discord server if you want!
Regards.

**Comment by Akryum** [comment]
A reproduction is a repository or codesandbox/stackbtliz/etc. that shows the issue you are describing
