### ISSUE TITLE
SFC Playground displays errors when dev tools is enabled

### ISSUE THREAD

**Issue by robokozo** [vuejs/devtools#1959]
### Version
6.4.2

### Browser and OS info
Chrome 106.0.5249.62 / Windows 10

### Steps to reproduce
Open browser (tested with chrome and firefox) to https://sfc.vuejs.org/
Add a line of valid code. e.g. const test = ref();

### What is expected?
No error to appear

### What is actually happening?
SFC playground displays an error reading:
"Cannot read properties of null (reading 'nextSibling')

---
Refreshing seems to fix it.
Changing versions seems to fix it.
This has started happening over the last few days

I first opened the ticket on vuejs/core: https://github.com/vuejs/core/issues/6779

**Comment by Akryum** [comment]
See https://github.com/vuejs/core/pull/6812
