### ISSUE TITLE
Vue.js devtools 6.4.5 非常的卡

### ISSUE THREAD

**Issue by zhangdaiscott** [vuejs/devtools#1987]
### What problem does this feature solve?

Vue.js devtools
6.4.5

非常的卡

**Comment by G1King** [comment]
vue3 不能用呢

**Comment by kobezone** [comment]
window 太卡了 没法用

**Comment by dingcang** [comment]
> window 太卡了 没法用

遇到同样的情况。

**Comment by WebGamer** [comment]
5.3.4 很流畅 6.x的版本还不稳定

**Comment by wuchuangqk** [comment]
> 项目使用的 vite，antdv，开启了 devtools 某一天突然开始卡顿，且在数据量大时页面直接崩溃，一直以为是 vite 配置或antdv使用不当，偶然间看到一个答案，关闭 devtools 瞬间丝滑了....

我以为是我路由的问题，切换页面特别卡，把路由代码折腾了半天，最后发现是devtools的问题……

**Comment by atom-7** [comment]
同样的问题,我怀疑还有内存泄露

**Comment by huangshuwei** [comment]
希望作者尽快修复，否则没法用，卡的怀疑人生

**Comment by mudoo** [comment]
这个项目是不是没有人管了？卡顿的问题印象里很早之前就有人反馈了，现在依旧没有解决，是无法解决吗？
我都已经快半年没有使用devTools，开发调试很不方便

**Comment by WebGamer** [comment]
![image](https://user-images.githubusercontent.com/56241499/235033456-c91938ef-0cd8-48dc-890e-74dca4e51114.png)
vue2 用5.x   vue3用6.x  亲测完美

**Comment by zhangdaiscott** [comment]
好像 6.5.0好一些了

**Comment by huangshuwei** [comment]
亲测， 6.5.0仍然很卡

**Comment by zhangzhengyi0220** [comment]
> 好像 6.5.0好一些了

依然卡的动不了，打开控制台就卡

**Comment by kiccer** [comment]
我用 devtools v6.5.1 的 performance 调试出来好像是组件库内使用了 resizeobserver 导致的卡顿。
