### ISSUE TITLE
Allow access to selected Pinia Store in console as with selected Vue Component

### ISSUE THREAD

**Issue by emahuni** [vuejs/devtools#1988]
### What problem does this feature solve?

The idea is to use a Pinia store that is selected in Pinia devtools the same way that you can use a selected Vue component, see below screenshots:

With Vue components one can select a component and immediately manipulate it in console using `$vm`:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/7290508/202885647-cadb9834-c147-4479-933e-6edabe2983c2.png">

A similar approach would go a long way to enable Pinia usage when a pinia store is selected:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/7290508/202885703-6303016e-e156-46bd-a581-fa1478989951.png">
on above shot, `$p` will refer to the selected Pinia store and is a shortcut of finding a component that is using the store, selecting it, then use it as `$vm.filtersStore` that is if the developer exposed the store.

**Comment by emahuni** [comment]
I normally use this to reset the store, manipulate other props or functions of the store manually to test things. If this works just like Vue components, this will be super duper great.

**Comment by Akryum** [comment]
The pinia <=> devtools integration is in the pinia repo, not here. 🙏
