### ISSUE TITLE
Vue2: missing Pinia tab with errors in console 

### ISSUE THREAD

**Issue by a-kriya** [vuejs/devtools#2017]
### Vue devtools version

6.4.5

### Link to minimal reproduction

https://github.com/a-kriya/vue2-pinia-devtools-bug

### Steps to reproduce & screenshots

- clone repro repo
- `npm i`
- `npm run dev`
- navigate to app (http://localhost:5173/)
- open browser devtools
- navigate to Vue.js devtools tab

### What is expected?

Inspectable Pinia state in Vue devtools, as seen here with the same app in Vue3:

![image](https://user-images.githubusercontent.com/26761352/212749476-da7853f1-bfcd-412b-ac86-832eefb7211e.png)

### What is actually happening?

Pinia tab is unavailable with errors in browser JS console.

![image](https://user-images.githubusercontent.com/26761352/212749639-dc3daccd-1a74-43af-90f8-5e82ce4e6aca.png)

### System Info

```shell
System:
    OS: Linux 5.4 Linux Mint
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    npm: 8.19.3 - /usr/bin/npm
  Browsers:
    Chromium: 96.0.4664.93
    Firefox: 108.0.2
  npmPackages:
    vue: ^2.7.14 => 2.7.14 

Removed some system info which I do not think is pertinent.
```

### Any additional comments?

Ran into the issue when trying to reproduce another possible bug w/ Pinia and different Vue versions.

**Comment by LinusBorg** [comment]
You forgot to install the plugin.

From the [docs](https://pinia.vuejs.org/getting-started.html#installation):

> If you are using Vue 2, you also need to install a plugin and inject the created pinia at the root of the app:
> ```js
> Vue.use(PiniaVuePlugin)
> ```
> **This will also add devtools support.**

**Comment by a-kriya** [comment]
Thank you.
