### ISSUE TITLE
Latest version not available for firefox.

### ISSUE THREAD

**Issue by ozamorowski** [vuejs/devtools#2023]
### Vue devtools version

6.4.5, 6.5

### Link to minimal reproduction

https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/?utm_content=collection&utm_medium=referral&utm_source=addons.mozilla.org

### Steps to reproduce & screenshots

On [extension page](https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/?utm_content=collection&utm_medium=referral&utm_source=addons.mozilla.org) the version is 6.4.5 while the latest release is 6.5.
The [chrome extension page](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en) shows version 6.5.

![Screen Shot 2023-01-31 at 12 21 16](https://user-images.githubusercontent.com/1939688/215747445-d81a23e3-efdd-41b4-b24d-90dbb3b26684.png)

### What is expected?

Latest release should be available.

### What is actually happening?

Old version is available.

### System Info

```shell
not related to system
```

**Comment by djpowers** [comment]
This came up in another issue, it looks like the new version is awaiting review by Mozilla (https://github.com/vuejs/devtools/issues/1974#issuecomment-1410664006) so hopefully it will become available soon.

**Comment by ShadowSpade** [comment]
can't wait for it to update!! it keeps refreshing by itself

**Comment by djpowers** [comment]
For anyone else waiting, the update just went live on AMO today: https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/

This issue can now be closed.

**Comment by ozamorowski** [comment]
> For anyone else waiting, the update just went live on AMO today: https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/
> 
> This issue can now be closed.

Finally!

**Comment by Tennyleaz** [comment]
Firefox addon still not updated?
![圖片](https://github.com/vuejs/devtools/assets/7089271/6d6adb89-d18a-40e8-aba0-c90f60186f5a)
