### ISSUE TITLE
An error occurred in hook 'getInspectorState' registered by plugin 'org.vuejs.vue2-internal' with payload

### ISSUE THREAD

**Issue by argentum-konstantinium** [vuejs/devtools#2031]
## Vue devtools version

6.5.0

### Link to minimal reproduction

https://github.com/argentum-konstantinium/vue-devtools-bug

### Steps to reproduce & screenshots

1. Create project with vue 2 and vuex (for vue 3 this error is not actual)
2. Create parent module with namespaced: false
3. Create childModule with namespaced: true
4. Open this in browser
5. Open vue devtools and inspect child module in vuex

### What is expected?

Success inspect child module in vuex

### What is actually happening?

Vue devtools throw error: 

![image](https://user-images.githubusercontent.com/64431957/223453254-9770d474-929a-4fbb-97be-bc0da58d638a.png)

```
backend.js:748 An error occurred in hook 'getInspectorState' registered by plugin 'org.vuejs.vue2-internal' with payload: Object

callHandlers @ VM2100 backend.js:748
callHook @ VM2100 backend.js:230
VM2100 backend.js:749 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at formatStoreForInspectorState (VM2100 backend.js:5790:30)
    at VM2100 backend.js:5465:27
    at handler (VM2100 backend.js:725:16)
    at DevtoolsHookable.callHandlers (VM2100 backend.js:746:17)
    at DevtoolsApi.callHook (VM2100 backend.js:230:26)
    at async DevtoolsApi.getInspectorState (backend.js:445:21)
    at async sendInspectorState (backend.js:2644:44)
```

### System Info

```shell
system: windows 11 (64 bit)
browser: chrome 110.0.5481.178 (64 bit)
```

**Comment by vushe** [comment]
This [recommendation](https://github.com/vuejs/devtools/issues/1669#issuecomment-1075733411) seems to work for me.

Also disabling [custom inspector](https://devtools.vuejs.org/plugin/api-reference.html#custom-inspector), as suggested in [this comment](https://github.com/vuejs/devtools/issues/1696#issuecomment-1039515798), fixes this issue.
