### ISSUE TITLE
devtools 不识别camelCase 形式命名的事件

### ISSUE THREAD

**Issue by dfjfj** [vuejs/devtools#2046]
### Vue devtools version

6.5.0

### Link to minimal reproduction

https://play.vuejs.org/#eNqNVM9PE0EU/lcme2C3Sdmi3moxeNCEu/HCctjsztKJ29nN7myBkJ4UtAgKAS8YiU0EookVPYBQ4a/p/ujJf8E3s90fRWJMmmbmzfe99+Z73+ya9NB11XaApbrUYLjl2jrDDzSKUMMkbWTYuu/PahJzTGfacCjTCcWeJgnEbZhlT3fzYwA8geA8dQOG5gj1scemOQzQ6Y4fP6aaVMsS1iBjWn68atRKXcHWNzziMliTlut4DK152KqiZZ0ZzQ6yPKeFZLiNnJ8XDYhDTVJreYjfW5Pu87waxSsCb2JLD2zIy5ugegvXgQMaaVKVRwwH0lJMmV9PIaiowLcdgfIxC1ylkiFAON+xsWo7S4rMmgS4chXxRQXVaiigUBR0NQs0Q1ymeUrYU91Gs2ghE3SNmECembkDCfg8oBPYhzvPR0dfIWRCb3Vk6baP007KnLsTnPhDLznp5hzmBbdQ7k1Qou5e8n0DfjcqpaxFEHKyfx86h/EopbtUhNocZgXUYMShqOwEAc11u6EcTCEevBgOzsLzH9Gbo2j/LHx1Gr07jbb7ciVjiLpqW7cDrAbUbxKLpUnH3UGz6cKDGXm0KCWIuQAT9syIYzb8NWq5DzUqVaUJS/3HU2pi3Sy/IyIcylZdzBF4hWkSAr6Bm44NQAgm386T671w/Wh49TE+ABUG4WYv3NmOT05//9qKtrrh+8Pk6ni03497/aT/CRLMPcOrgavC7EQG3TR5m9lj+/cDSy0sIuk8cYswGGfq1Eew8ZUFuVBJXoQJaDQf6riYgttQfjxQG7PMTJBJnKhM95YwqMbnJSZELKRkoKmpYj2bUVXmkZZSqeQugReUnByHb3fjwW7YPwBxkpdfYDG86A4vX4NdUhi/gFLuuFrMvnhUJePxYvm+ZPexHYTjOghDJEuk25BbkfNRhdfr4eYhNDHqXcipAYWLoOPo53r8+TKFRb0NHv1bELi0DF+ySb9JnT885RsS

### Steps to reproduce & screenshots

打开开发者工具，查看TodoInput子组件，会发现黄色的⚠标志，说这个事件没有在emits中声明。程序是执行正确的噢。

### What is expected?

期待能正常识别

### What is actually happening?

没有识别

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 7.03 GB / 15.92 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.19041.1566
```

**Comment by Azurewarth0920** [comment]
Simple translation TL;NR

`defineEmits(['fooBar'])` now cannot be correctly recognized by the devtool but `defineEmits(['foo-bar'])` can, because a name-case-processing problem.

**Comment by Azurewarth0920** [comment]
> https://github.com/vuejs/devtools/issues/2046#issuecomment-1507144281

This will be fixed with: https://github.com/vuejs/devtools/pull/2051
