### ISSUE TITLE
Vue devtools doesn't show setup state for a component imported from a Vite built Vue library

### ISSUE THREAD

**Issue by segevfiner** [vuejs/devtools#2061]
### Vue devtools version

6.5.0

### Link to minimal reproduction

https://github.com/segevfiner/vite-devtools-lib-issue

### Steps to reproduce & screenshots

1. `pnpm build` in `packages/foo`
2. `pnpm dev` in `apps/bar`
3. Open the browser & the Vue devtools.
4. Check the inspector for the `HelloWorld` component.

If you switch the import in `apps/bar/src/App.vue` to import the `HelloWorld` component from `./components/HelloWorld.vue` instead, the setup state does show in the Vue devtools.

### What is expected?

It shows setup state for the component imported from the `foo` library.

![image](https://user-images.githubusercontent.com/24731903/235438483-a497f771-6a2e-4229-a6a2-38783260c547.png)

### What is actually happening?

It doesn't.

![screenshot](https://user-images.githubusercontent.com/24731903/235438022-d3e7f38b-cab9-4a21-a0de-0eaf3904c18c.png)

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 104.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 9.6.5 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
```

**Comment by Azurewarth0920** [comment]
It is the limitation on the production build.

The devtool relies on the property `setupState` in the instance when development.
But the `setupState` is not exposed in the production mode. In other words, you cannot inspect the internal state of compiled component.

**Comment by segevfiner** [comment]
Can we tweak the build to produce a build conditional on `process.env.NODE_ENV` for production vs development build so that the library has debugging available when built as such?

**Comment by Azurewarth0920** [comment]
> Can we tweak the build to produce a build conditional on process.env.NODE_ENV for production vs development build so that the library has debugging available when built as such?

Nope, most of the libraries are pre-built, so when importing the libraries they are already in "production mode".

Then I found another approach to solve this and pulled a request.

**Comment by segevfiner** [comment]
I'm talking about tweaking the build process of my own library to support such a mode. As a flag to plugin vue or something.

**Comment by Azurewarth0920** [comment]
> I'm talking about tweaking the build process of my own library to support such a mode. As a flag to plugin vue or something.

At this time, due to the limitation of the compiler. The answer is **NO**.
Or you can try not to compile your library and import `.vue` file directly.

**Comment by segevfiner** [comment]
So I guess this is a feature request to the compiler. I'll figure out what's the right repo to request that

**Comment by Azurewarth0920** [comment]
Somehow I think it is the mis-implementation on devtool.

It will be fixed by https://github.com/vuejs/devtools/pull/2091

**Comment by segevfiner** [comment]
So this might also tie into https://github.com/vitejs/vite-plugin-vue/issues/36 which was about the `name` but I guess there are also other differences in building components between release and debug.

**Comment by s-nesbigall** [comment]
Any news on this? I still have this problem in 6.5.1. It seems the merge request never got accepted.
