### ISSUE TITLE
Bump manifest from v2 to v3

### ISSUE THREAD

**Issue by gweesin** [vuejs/devtools#2126]
### What problem does this feature solve?

Manifest version 2 is deprecated, and support will be removed in 2023. We can see [The transition of Chrome extensions to Manifest V3](https://developer.chrome.com/blog/mv2-transition/) for more details

**Comment by Igloczek** [comment]
Dupe of #1917

**Comment by gweesin** [comment]
Exactly. Thank you for your aply, and I hope that can merge main soon.🙏🏻
