### ISSUE TITLE
Devtools toolbar icon and popover warning if Vue is out-of-date

### ISSUE THREAD

**Issue by ghost** [vuejs/devtools#414]
I'm new to vue and slowly picking up. Previously i tried react and I liked its tooling so much. I believe the vue devtools will be more powerful if we add few more options which leads to a great experience . Here are few of my suggestions which i recommend.

**01. Want status changing icons like react for vue dev tools on chrome header panel.**
![capture-1](https://user-images.githubusercontent.com/13760265/30478220-ce8230be-9a2d-11e7-9979-aa79608dc5bc.PNG)

**02. Want a "select button" through which i can hover over the vuejs app and on click or hover over respective component get highlighted in virtual DOM code.**
![capture](https://user-images.githubusercontent.com/13760265/30478200-b4df98e0-9a2d-11e7-835b-3fe0816f3d9b.PNG)
_Screenshot of Vue Dev Tools:_
![capture-2](https://user-images.githubusercontent.com/13760265/30478225-d2e9a646-9a2d-11e7-9a16-c26135f0d775.PNG)

**Comment by Akryum** [comment]
2) will be implemented by #476 and you will soon be able to Right-click a component in the page with #479.

**Comment by Akryum** [comment]
Implemented in v6.
