### ISSUE TITLE
Editable props would be a nice improvement

### ISSUE THREAD

**Issue by wolandec** [vuejs/devtools#517]
Hi, thank you for the nice tool!

I noticed that we can't set props from devtools as we can in https://devtools.vuejs.org/ .
<img width="549" alt="image" src="https://github.com/vuejs/devtools-next/assets/5939240/4989c07d-8b10-4319-b4d3-f80f00415f86">

Is there any plan to thave the same functionality in `devtools-next`?

**Comment by mrleblanc101** [comment]
I wonder why v7 was released without this feature, this is an annoying regression.

**Comment by alexzhang1030** [comment]
We've gonna support it soon.
