### ISSUE TITLE
inspector  keymap ?

### ISSUE THREAD

**Issue by 1571312541** [vuejs/devtools#622]

**Comment by duowb** [comment]
Mac
Use Shift + Option + D to toggle DevTools
Use Command + K to toggle Command Palette

Win
Use Shift + Alt + D to toggle DevTools
Use Alt  + K to toggle Command Palette

Is this it?

**Comment by J-Sek** [comment]
Previous version had `Alt` + `S` that was very helpful to quickly enable component selector. Now we have to squeeze eyes, find the small icon in the corner of the devtools panel, carefully point and click.. you get the idea. Some people may miss it, including me.

**Comment by webfansplz** [comment]
#684
