### ISSUE TITLE
Provide an option to disable bounce effect in graph panel

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/devtools#633]
I greatly dislike the bounce effect in graph panel, and I think that's not my own taste.

There are some people which can feel dizzy when watching complicated animations, and I am one of them. Not kidding, I feel very bad **every time I try to enter the graph panel**, that's also why CSS standard have a `Prefers-reduced-motion` media in a11y part.

We can respect the `Prefers-reduced-motion`, together with a higher priority option to control the animation behavior, for better a11y :)

**Comment by duowb** [comment]
Maybe the same as issue #567?
