### ISSUE TITLE
vue.js not detected since Version 7.5.6

### ISSUE THREAD

**Issue by frufin** [vuejs/devtools#653]
Hi,
Using Vue-cli 3 and Vue v2.7 on Mac OS 10.14.6, from today (7.5.6 version new release), my vue apps are not detected any more...
Everything was (quite) fine before.

**Comment by webfansplz** [comment]
The v7 version of devtools only supports Vue3. If your application is still using Vue2, please install the [v6 version](https://chromewebstore.google.com/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp?utm_source=ext_sidebar?utm_source=ext_sidebar). If you're still using v5 version, you can install it [here](https://chromewebstore.google.com/detail/vuejs-devtools-v5/hkddcnbhifppgmfgflgaelippbigjpjo).
