### ISSUE TITLE
chrome extensions: devtools: Unnecessary pinia installed logs will be printed (Refresh will)

### ISSUE THREAD

**Issue by warmthsea** [vuejs/devtools#671]
### Open tools
![screenshots](https://github.com/user-attachments/assets/22a57791-7205-4076-b632-360b16c7f8e4)

![image](https://github.com/user-attachments/assets/9cc33193-9f92-40fb-af2c-9ef4b169a4bb)

![image](https://github.com/user-attachments/assets/ebe60512-dac2-4d40-8d00-50213ab005d9)

### Off tools
![image](https://github.com/user-attachments/assets/d4106e1e-6259-4106-a086-6d045ca34255)

**Comment by webfansplz** [comment]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/e65dbbd4-820e-4de3-9e03-5e195e56a192">
You can disable it with this option.

**Comment by webfansplz** [comment]
> <img alt="image" width="388" src="https://private-user-images.githubusercontent.com/22515951/382170421-e65dbbd4-820e-4de3-9e03-5e195e56a192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzAzMTgsIm5iZiI6MTczMDQzMDAxOCwicGF0aCI6Ii8yMjUxNTk1MS8zODIxNzA0MjEtZTY1ZGJiZDQtODIwZS00ZGUzLTllMDMtNWUxOTVlNTZhMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAzMDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTRhODFhZTQxOTJjYmNhNTBlNWJmNDA3MWY3YTJjNTIzYjA5ZjgxYjk5YzllNjQ1ODQ1MWU5OTYxNGQxMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AnNGj1bWAUdpdqjXmUQHic9wRLHYvumAYc7oF7E8jqc"> 

You can disable it with this option.

**Comment by warmthsea** [comment]
Thanks
