### ISSUE TITLE
Cant drag over text anymore and copy + colors hurt the eye

### ISSUE THREAD

**Issue by Rinooh** [vuejs/devtools#673]
Recently the new version got downloaded, I can see some improvements but overall the basic functionality I used the most doesn't work anymore for me.

I used to inspect my elements so I could copy any data or params from a component, however this is no longer possible and it can only be done by doing a copy value or a copy path which should be a combined function??

Next to that the new colors with the design hurts the eyes, either the font is too thin or the colors are just making it all look awful

Other than that, great improvements but these 2 things are bugging me, especially the copying part which is an issue

**Comment by alexzhang1030** [comment]
Hey, have tried dark mode? This color scheme forked by https://github.com/vuejs/ui, was originally designed as a Vue design system.

I think most of the time, dark mode does not hurt eyes.

<img width="963" alt="image" src="https://github.com/user-attachments/assets/9f3cadfb-1c70-40d2-b3cf-279d9ac579fb">

**Comment by Rinooh** [comment]
> Hey, have tried dark mode? This color scheme forked by https://github.com/vuejs/ui, was originally designed as a Vue design system.
> 
> I think most of the time, dark mode does not hurt eyes.
> 
> <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/49969959/382286095-9f3cadfb-1c70-40d2-b3cf-279d9ac579fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjkyMTQsIm5iZiI6MTczMDQ2ODkxNCwicGF0aCI6Ii80OTk2OTk1OS8zODIyODYwOTUtOWYzY2FkZmItMWM3MC00MGQyLWIzY2YtMjc5ZDlhYzU3OWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEzNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZDU5MjMyODJiOWM4NmFkNTg0YTQ5NDhiZThhMTJhNDZjZDhmZmJlYTA2NTZkYzMwMzU1MjRjMmU3MGM0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mk8TJI_BFAx2nug1sxH9b4T-0u4_AHCp_gSkTbJWD3E">

Yes, Darkmodus is currently on however it looked fine in the old version. This newer version is a pain to look at

**Comment by alexzhang1030** [comment]
Is this too bright or could there be other issue? How can we improve it

**Comment by Rinooh** [comment]
> Is this too bright or could there be other issue? How can we improve it

I'd say one solution would be offering a theme mode 'Classic' or something into that direction which uses the older version its styles that would solve it the quickest
