### ISSUE TITLE
Refine color contrast for devtools dark mode

### ISSUE THREAD

**Issue by alexzhang1030** [vuejs/devtools#685]
Originally posted by [@Rien](https://github.com/Rinooh)

I'd say currently color contrast is terrible. Excessive contrast can lead to eye strain.

See below:

<img width="858" alt="image" src="https://github.com/user-attachments/assets/61f1caac-ecba-4b2a-a1e0-a2d5cf927fb3">

**Comment by mrleblanc101** [comment]
https://github.com/vuejs/devtools/issues/677
