### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'state')

### ISSUE THREAD

**Issue by sardor01** [vuejs/devtools#707]
### Environment:
- Operating System: Darwin
- Node Version:     v20.10.0
- Package Manager:  pnpm@9.12.3

### Reproduction:
https://github.com/sardor01/vue-devtools-issue-repro

### Steps to reproduce the bug
- Start app in dev mode
- Open vue devtools
- Click on the pinia tab in devtools
- hard refresh app page
- See error traceback in browser console

### Describe the bug:
I am getting this issue in the console:

![Screenshot 2024-11-20 at 06 49 09](https://github.com/user-attachments/assets/36786d52-79fe-4739-ab21-5b0a67023c09)

**Comment by webfansplz** [comment]
I tried to reproduce it with the https://github.com/sardor01/vue-devtools-issue-repro repo, but I could not. Any special handle steps or environments?
