### ISSUE TITLE
Upgrade vite-plugin-inspect to v0.10.0 to support Vite 6

### ISSUE THREAD

**Issue by HummingMind** [vuejs/devtools#713]
Please upgrade vite-plugin-inspect to v0.10.0 to support Vite 6
[Link](https://github.com/antfu-collective/vite-plugin-inspect/releases/tag/v0.10.0)

Thank you!

**Comment by webfansplz** [comment]
> I am trying to install vite v6, and I'm getting this warning ![Screenshot 2024-11-29 at 15 24 27](https://private-user-images.githubusercontent.com/58367523/391053238-83151c7a-97e5-4985-a480-e2b13f86b5d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzY1NzIsIm5iZiI6MTczMjg3NjI3MiwicGF0aCI6Ii81ODM2NzUyMy8zOTEwNTMyMzgtODMxNTFjN2EtOTdlNS00OTg1LWE0ODAtZTJiMTNmODZiNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEwMzExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZjhhNDhlZjMyYjgyMDlmM2NjYzY3NWRjNzViNDA2YzQ1ZmViOTg4OTY4NTMxNTdiZmI0Yjg2NGIxYTViMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sTl2opcWNTYXasa57v0T2ixEjNs-7g8d96hovqQPMMU)

`vite-plugin-inspect` v0.10 has breaking changes (See: https://github.com/antfu-collective/vite-plugin-inspect?tab=readme-ov-file#install),  v0.8.x can compatible with both Vite 5 & 6. BTW, this warning won't affect the usage.

**Comment by HummingMind** [comment]
I use npm, so I used an override for v0.8.x:

![image](https://github.com/user-attachments/assets/7e49cb4f-134f-4d18-9db6-a7927cb32283)

Thay way no warning during `npm install` and/or `npm update`

**Comment by HummingMind** [comment]
@webfansplz looks like they just releases version v0.8.9 that supports both Vite 5 and Vite 6 without breaking changes.
So if you get a chance to upgrade from 0.8.8 to 0.8.9 that would be awesome!

Thank you! 🍻
