### ISSUE TITLE
vuedevtools style exception when used with msw v2.6.4+

### ISSUE THREAD

**Issue by jerrywu001** [vuejs/devtools#717]
[vuedevtools-msw2.6.4.zip](https://github.com/user-attachments/files/17953406/vuedevtools-msw2.6.4.zip)

from this version msw@2.6.4, [commit](https://github.com/mswjs/msw/commit/2fa98c327acc51189f87789d9155c4ec57be2299)

1. download the `vuedevtools-msw2.6.4.zip`
2. `pnpm i`
3. `npm run dev`

**Follow the steps below to reproduce the problem**

![image](https://github.com/user-attachments/assets/a29c984f-98c3-4e84-ae9c-25fce9abd0b6)

**like this**

![image](https://github.com/user-attachments/assets/62dc30b7-ee5d-440c-b97b-d272439b6f8d)

**then click the "vue logo"**

**got it**

![image](https://github.com/user-attachments/assets/4164c2ba-b4df-43ef-bbd7-2fd07665909e)

**Comment by kleinfreund** [comment]
I _think_ I'm seeing the same issue in our application (though I don't know under which conditions it reproduces). The symptom is that, sometimes (it's very much unclear when this happens exactly), the styles sourced via `<link rel="stylesheet" href="http://localhost:5173/@id/virtual:vue-devtools-path:overlay/devtools-overlay.css">` don't seem to be applied to the vue devtools UI (though the `link` element is present).

We do also use msw.

**Comment by jerrywu001** [comment]
Fix from msw@2.6.8
