### ISSUE TITLE
Cannot select a component in another App if there are multiple Apps on the page

### ISSUE THREAD

**Issue by kevinluo201** [vuejs/devtools#718]
Hi there 😀, I've checked https://github.com/vuejs/devtools/issues/454 but I am not sure if it is the same issue. The problem happens when there are multiple apps on a page. I cannot select a component unless I switch to the app which contains that component. Is it designed like that? However, when the mouse hovers over the component, it does show the name of the component but nothing happens when it is clicked, which is pretty confusing.

https://github.com/user-attachments/assets/782d4168-cabb-48d7-bdd6-541ec8f81cb3

The code is like this:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
</head>
<body>
  <div id="app">
    <my-component title="Hello"></my-component>
  </div>

  <div id="app2">
    <my-component2 title="Hello2"></my-component2>
  </div>

  <script>
    const { createApp, ref } = Vue

    const app = createApp()
    app.component(
      'MyComponent',
      {
        template: `
          <div>
            <h1>{{ title }}</h1>
          </div>
        `,
        props: {
          title: String,
        }
      }
    )
    app.mount('#app')

    const app2 = createApp()
    app2.component(
      'MyComponent2',
      {
        template: `
          <div>
            <h1>{{ title }}</h1>
          </div>
        `,
        props: {
          title: String,
        }
      }
    )
    app2.mount('#app2')
  </script>
</body>
</html>
```

**Comment by stuartromanek** [comment]
Same. Bad experience. This is often the first thing you do when using the dev tools

**Comment by kevinluo201** [comment]
https://github.com/vuejs/devtools/pull/748
I tried to solve this problem but I ran into a big problem. Can anyone guide me or give my a hint?🙏
I found that it works only if I click on a component whose `componentTreeContainer` has been rendered at least once. Otherwise, `rpc.value.inspectComponentInspector()` just return `{id: "<AppID>:undefined"}` rather than `{id: "<AppID>:<NodeNumber>"}`

https://github.com/user-attachments/assets/b5736199-137f-40e4-a860-c0e362dc37af

**Comment by kevinluo201** [comment]
@alexzhang1030 I just finished the PR. I think it can be refined, but the function is implemented.
