### ISSUE TITLE
Bump vite-plugin-inspect

### ISSUE THREAD

**Issue by tom-id-au** [vuejs/devtools#722]
Vite plugin inspect can now be bumped to 0.8.9:

https://github.com/antfu-collective/vite-plugin-inspect/releases/tag/v0.8.9

This will avooid this warning with vite 6:

npm warn ERESOLVE overriding peer dependency
npm warn While resolving: vite-plugin-inspect@0.8.8
npm warn Found: vite@6.0.2
npm warn node_modules/vite
npm warn   dev vite@"^6.0.2" from the root project
npm warn   7 more (@vitejs/plugin-vue, vite-hot-client, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer vite@"^3.1.0 || ^4.0.0 || ^5.0.0-0" from vite-plugin-inspect@0.8.8
npm warn node_modules/vite-plugin-vue-devtools/node_modules/vite-plugin-inspect
npm warn   vite-plugin-inspect@"0.8.8" from vite-plugin-vue-devtools@7.6.7
npm warn   node_modules/vite-plugin-vue-devtools
npm warn
npm warn Conflicting peer dependency: vite@5.4.11
npm warn node_modules/vite
npm warn   peer vite@"^3.1.0 || ^4.0.0 || ^5.0.0-0" from vite-plugin-inspect@0.8.8
npm warn   node_modules/vite-plugin-vue-devtools/node_modules/vite-plugin-inspect
npm warn     vite-plugin-inspect@"0.8.8" from vite-plugin-vue-devtools@7.6.7
npm warn     node_modules/vite-plugin-vue-devtools

**Comment by zermx** [comment]
WARN  Issues with peer dependencies found
.
└─┬ vite-plugin-vue-devtools 7.6.7
  └─┬ vite-plugin-inspect 0.8.8
    └── ✕ unmet peer vite@"^3.1.0 || ^4.0.0 || ^5.0.0-0": found 6.0.2

**Comment by SebiBasti** [comment]
`vite-plugin-inspect 0.8.9` has vite 6 support.
