### ISSUE TITLE
Failed to launch in WXT - ERROR Invalid URL

### ISSUE THREAD

**Issue by lei1248276** [vuejs/devtools#729]
In WXT, an error appears after starting dev: ERROR Invalid URL 
           
<img width="1048" alt="截屏2024-12-07 15 38 16" src="https://github.com/user-attachments/assets/752eda88-3c86-4829-8de0-27e665b91127">

**Steps to Reproduce:**
1. Run `pnpm dlx wxt@latest init` to create a new project
2. Use [vue-devtools](https://devtools-next.vuejs.org/help/faq#how-to-work-with-wxt)

**Current solution:**
1. Remove **.ts** files from the entrypoints directory

**Comment by webfansplz** [comment]
Try to use with 👉 [wxt usage docs](https://devtools-next.vuejs.org/help/faq#how-to-work-with-wxt)

**Comment by lei1248276** [comment]
After upgrading WXT to v0.19.20, everything is fine now
