### ISSUE TITLE
Map display improvements (length, pagination)

### ISSUE THREAD

**Issue by axp-dev** [vuejs/devtools#750]
### What problem does this feature solve?
* Number of elements in the Map 
* Hide Map Default. I use Map to store large data. When I open DevTools everything hangs. Since DevTools renders all the Map items. I think the same behavior as the array will be just right

### What does the proposed API look like?
![Map](https://pp.userapi.com/c831409/v831409729/18146b/YaYfdVE42kM.jpg)

**Comment by rajzshkr** [comment]
I can pick this enhancement.
