### ISSUE TITLE
Stop recording doesn't work

### ISSUE THREAD

**Issue by Botz** [vuejs/devtools#830]
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 70.0.3538.102 (Offizieller Build) (64-Bit), MacOs Sierra

### Steps to reproduce
Got to the Vuex Tab and click on Recording to disable it. Now it is Paused.

### What is expected?
Devtools doesn't record mutations

### What is actually happening?
Devtools records mutations.

**Comment by DoubleB123** [comment]
Yep this is happening to me also on the same release. This is really frustrating since I have a lot of vuex actions and data so I get an out of memory error and the dev tools and page crash.

**Comment by Akryum** [comment]
I can't reproduce on the dev application.

**Comment by DoubleB123** [comment]
@Botz any chance you are using Vuex ORM (https://github.com/vuex-orm/vuex-orm)? I'm using that so maybe that could be causing the issue.

I'll see if I can make a reproducible demo.

**Comment by Botz** [comment]
Yes i do

**Comment by Akryum** [comment]
We would need a minimal runnable reproduction.

**Comment by DoubleB123** [comment]
Ok, the issue is probably something with Vuex ORM then, I'll try and make a reproduction.

**Comment by senritsu** [comment]
May be related to #1003, although in my case it only incorrectly records after reloading the page. After manually stopping recording it does indeed stop (until the next page reload).
