### ISSUE TITLE
Object.entries doesn't exist in older browsers

### ISSUE THREAD

**Issue by dacotagh** [vuejs/devtools#949]
### Version
5.0.6

### Browser and OS info
Chrome 51/Windows 7

### Steps to reproduce
Turned on Chrome extensions
Choose Vue panel in development panel
Choose any component in list

### What is expected?
Expected to work

### What is actually happening?
backend.js:1982 Uncaught TypeError: Object.entries is not a function

---
Polyfill should be added for Object.entries

**Comment by beginnerBate** [comment]
how to resolve this problem？

**Comment by dacotagh** [comment]
Use polyfill somehow: https://github.com/tc39/proposal-object-values-entries
